export const UPDATE_SEND_RECOGNITION_FORM = 'UPDATE_SEND_RECOGNITION_FORM';
export const SET_LIST_RATING_CRITERIA_GROUPS =
  'SET_LIST_RATING_CRITERIA_GROUPS';
export const SET_WALLET_OVERVIEW = 'SET_WALLET_OVERVIEW';
export const CHANGE_SEARCH_USER_QUERY = 'CHANGE_SEARCH_USER_QUERY';
export const CHANGE_SEARCH_USER_DEPARTMENT_ID =
  'CHANGE_SEARCH_USER_DEPARTMENT_ID';

export const SET_BRANCHES = 'SET_BRANCHES';
export const SELECT_BRANCH_TEMP = 'SELECT_BRANCH_TEMP';
export const APPLY_SELECTED_BRANCHES = 'APPLY_SELECTED_BRANCHES';
export const CLEAR_SELECTED_BRANCHES_TEMP = 'CLEAR_SELECTED_BRANCHES_TEMP';
export const INIT_SELECTED_BRANCHES_TEMP = 'INIT_SELECTED_BRANCHES_TEMP';
export const CLEAR_SEARCH_USER_DATA = 'CLEAR_SEARCH_USER_DATA';
export const CLEAR_SELECTED_BRANCHES = 'CLEAR_SELECTED_BRANCHES';
export const SET_SEARCH_USER_LIST = 'SET_SEARCH_USER_LIST';
export const LOAD_MORE_SEARCH_USER = 'LOAD_MORE_SEARCH_USER';
export const CLEAR_SEND_RECOGNITION_FORM = 'CLEAR_SEND_RECOGNITION_FORM';
export const CHANGE_SHOW_HIDE_CONFIRM_SEND_MODAL =
  'CHANGE_SHOW_HIDE_CONFIRM_SEND_MODAL';
export const CHANGE_SHOW_HIDE_SUCCESS_SEND_MODAL =
  'CHANGE_SHOW_HIDE_SUCCESS_SEND_MODAL';
export const CHANGE_SHOW_HIDE_CONFIRM_RECALL_MODAL =
  'CHANGE_SHOW_HIDE_CONFIRM_RECALL_MODAL';
export const CHANGE_SHOW_HIDE_SUCCESS_RECALL_MODAL =
  'CHANGE_SHOW_HIDE_SUCCESS_RECALL_MODAL';
export const SET_VIEW_POINT_HISTORY = 'SET_VIEW_POINT_HISTORY';
export const SET_HISTORY_RECOGNITION = 'SET_HISTORY_RECOGNITION';
export const CLEAR_HISTORY_RECOGNITION = 'CLEAR_HISTORY_RECOGNITION';
export const CLEAR_RECOGNITION = 'CLEAR_RECOGNITION';
export const SET_SINGLE_HISTORY_RECOGNITION = 'SET_SINGLE_HISTORY_RECOGNITION';
export const SET_MONTHS = 'SET_MONTHS';
export const SELECT_MONTH_FILTER_HISTORY_TEMP =
  'SELECT_MONTH_FILTER_HISTORY_TEMP';
export const SELECT_ORDER_FILTER_HISTORY_TEMP =
  'SELECT_ORDER_FILTER_HISTORY_TEMP';
export const APPLY_FILTER_HISTORY = 'APPLY_FILTER_HISTORY';
export const CLEAR_FILTER_HISTORY_TEMP = 'CLEAR_FILTER_HISTORY_TEMP';
export const INIT_FILTER_HISTORY_TEMP = 'INIT_FILTER_HISTORY_TEMP';
export const SELECT_ALL_MONTH_FILTER_HISTORY_TEMP =
  'SELECT_ALL_MONTH_FILTER_HISTORY_TEMP';
export const SET_ENABLE_SCROLL_CHILD_TAB_VIEW =
  'SET_ENABLE_SCROLL_CHILD_TAB_VIEW';
export const SET_SINGLE_REWARD = 'SET_SINGLE_REWARD';
export const SET_REWARDS = 'SET_REWARDS';
export const CLEAR_REWARDS = 'CLEAR_REWARDS';
export const CLEAR_SINGLE_REWARD = 'CLEAR_SINGLE_REWARD';
export const SET_REWARD_CATEGORY = 'SET_REWARD_CATEGORY';
export const SET_TOP_RECENT_SENDER = 'SET_TOP_RECENT_SENDER';
export const SET_CLAIM_REWARD_EXPIRED_AT = 'SET_CLAIM_REWARD_EXPIRED_AT';
export const SET_REWARD_CATEGORIES = 'SET_REWARD_CATEGORIES';
export const CLEAR_REWARD_CATEGORIES = 'CLEAR_REWARD_CATEGORIES';
export const SET_SEARCH_REWARDS_QUERY = 'reward/SET_SEARCH_REWARDS_QUERY';
export const CLEAR_SEARCH_REWARDS_QUERY = 'CLEAR_SEARCH_REWARDS_QUERY';
export const CHANGE_SORT_REWARDS = 'CHANGE_SORT_REWARDS';
export const SET_RECOGNITION_REPLY_TEMPLATE = 'SET_RECOGNITION_REPLY_TEMPLATE';
export const SET_RECOGNITION_REPLIES = 'SET_RECOGNITION_REPLIES';
export const CREATE_RECOGNITION_REPLY = 'CREATE_RECOGNITION_REPLY';
export const CLEAR_RECOGNITION_REPLY = 'CLEAR_RECOGNITION_REPLY';
export const TOGGLE_IS_NEED_TO_SCROLL = 'TOGGLE_IS_NEED_TO_SCROLL';
export const UPDATE_COINS_AFTER_CONVERT_TO_BUDGET =
  'UPDATE_COINS_AFTER_CONVERT_TO_BUDGET';
export const SET_RECOGNITION_SCHEMES = 'SET_RECOGNITION_SCHEMES';
export const SET_RECOGNIZED_EMPLOYEES = 'SET_RECOGNIZED_EMPLOYEES';
export const SET_RECOGNITION_PROGRAM = 'SET_RECOGNITION_PROGRAM';
export const REMOVE_RECOGNIZE_EMPLOYEE = 'REMOVE_RECOGNIZE_EMPLOYEE';
export const UPDATE_RECOGNITION_EMPLOYEE = 'UPDATE_RECOGNITION_EMPLOYEE';
export const APPLY_MESSAGE_FOR_ALL_PARTICIPANTS =
  'APPLY_MESSAGE_FOR_ALL_PARTICIPANTS';
export const CLEAR_CREATE_RECOGNITION_BY_PROGRAM_REQ_MODEL =
  'CLEAR_CREATE_RECOGNITION_BY_PROGRAM_REQ_MODEL';
export const UPDATE_SINGLE_HISTORY_RECOGNITION =
  'UPDATE_SINGLE_HISTORY_RECOGNITION';
export const SET_RECOGNITION_COMMENTS = 'SET_RECOGNITION_COMMENTS';
export const ADD_NEW_RECOGNITION_COMMENT = 'ADD_NEW_RECOGNITION_COMMENT';
export const ADD_SELECTED_EMPLOYEE = 'ADD_SELECTED_EMPLOYEE';
export const ADD_ALL_SELECTED_EMPLOYEE = 'ADD_ALL_SELECTED_EMPLOYEE';
export const REMOVE_SELECTED_EMPLOYEE = 'REMOVE_SELECTED_EMPLOYEE';
export const REMOVE_ALL_SELECTED_EMPLOYEE = 'REMOVE_ALL_SELECTED_EMPLOYEE';
export const MAP_RECOGNIZED_TO_SELECTED_EMPLOYEES =
  'MAP_RECOGNIZED_TO_SELECTED_EMPLOYEES';
export const SET_ALL_RECOGNITION_SCHEMES = 'SET_ALL_RECOGNITION_SCHEMES';
export const SET_RECOGNITION_PROGRAM_FILTER = 'SET_RECOGNITION_PROGRAM_FILTER';
export const RESET_RECOGNITION_PROGRAM_FILTER =
  'RESET_RECOGNITION_PROGRAM_FILTER';
export const SET_MANAGER_POINT_CAP = 'SET_MANAGER_POINT_CAP';

export const CHECK_IN_EVENT = 'CHECK_IN_EVENT';
export const CHECK_IN_EVENT_SUCCESS = 'CHECK_IN_EVENT_SUCCESS';
export const CHECK_IN_EVENT_FAILED = 'CHECK_IN_EVENT_FAILED';

export const GET_LIST_SELF_RECOGNITION = 'GET_LIST_SELF_RECOGNITION';
export const GET_LIST_SELF_RECOGNITION_SUCCESS =
  'GET_LIST_SELF_RECOGNITION_SUCCESS';
export const GET_LIST_SELF_RECOGNITION_FAILED =
  'GET_LIST_SELF_RECOGNITION_FAILED';
export const SET_LEVEL_ID_SELF_RECOGNITION = 'SET_LEVEL_ID_SELF_RECOGNITION';
export const SET_ATTACHMENT = 'SET_ATTACHMENT';
export const REMOVE_ITEM_ATTACHMENT = 'REMOVE_ITEM_ATTACHMENT';
export const REMOVE_ALL_ITEM_ATTACHMENT = 'REMOVE_ALL_ITEM_ATTACHMENT';
export const SET_ACTIVE_SELF_RECOGNITION = 'SET_ACTIVE_SELF_RECOGNITION';
export const CLEAR_ACTIVE_SELF_RECOGNITION = 'CLEAR_ACTIVE_SELF_RECOGNITION';
export const SET_LEVEL_POINT = 'SET_LEVEL_POINT';
export const CLEAR_NOTE = 'CLEAR_NOTE';
export const SET_RECOGNITION_LOADING = 'SET_RECOGNITION_LOADING';
export const SET_USER_MANAGERS = 'SET_USER_MANAGERS';
export const CLEAR_USER_MANAGERS = 'CLEAR_USER_MANAGERS';
export const UPDATE_RECOGNISE_EMPLOYEE = 'UPDATE_RECOGNISE_EMPLOYEE';
export const UPDATE_POINT_FOR_GROUP_RECOGNITION =
  'UPDATE_POINT_FOR_GROUP_RECOGNITION';
export const SET_DEPARTMENTS = 'SET_DEPARTMENTS';
export const UPDATE_DEPARTMENTS = 'UPDATE_DEPARTMENTS';
export const UPDATE_SELECTED_EMPLOYEE = 'UPDATE_SELECTED_EMPLOYEE';
export const SET_REWARD_LOCATIONS = 'SET_REWARD_LOCATIONS';
export const UPDATE_REWARD_LOCATIONS = 'UPDATE_REWARD_LOCATIONS';
export const CLEAR_REWARD_LOCATIONS = 'CLEAR_REWARD_LOCATIONS';
export const APPLY_FILTER_REWARD_LOCATIONS = 'APPLY_FILTER_REWARD_LOCATIONS';
export const SET_RECOGNITION_HISTORY_FILTER = 'SET_RECOGNITION_HISTORY_FILTER';
