export const SET_NEWS = 'SET_NEWS';
export const SET_LATEST_NEWS = 'SET_LATEST_NEWS';
export const SET_FEATURED_DOCUMENTS = 'SET_FEATURED_DOCUMENTS';
export const SET_DOCUMENTS = 'SET_DOCUMENTS';
export const SET_ARTICLE_RELATED = 'SET_ARTICLE_RELATED';
export const CLEAR_NEWS_AND_DOCUMENTS = 'CLEAR_NEWS_AND_DOCUMENTS';
export const CLEAR_NEWS = 'CLEAR_NEWS';
export const CLEAR_DOCUMENTS = 'CLEAR_DOCUMENTS';
export const SET_MONTHS = 'SET_MONTHS';
export const SELECT_MONTH_FILTER_NEWS_AND_DOCUMENTS_TEMP =
  'SELECT_MONTH_FILTER_NEWS_AND_DOCUMENTS_TEMP';
export const SELECT_ORDER_FILTER_NEWS_AND_DOCUMENTS_TEMP =
  'SELECT_ORDER_FILTER_NEWS_AND_DOCUMENTS_TEMP';
export const APPLY_FILTER_NEWS_AND_DOCUMENTS =
  'APPLY_FILTER_NEWS_AND_DOCUMENTS';
export const CLEAR_FILTER_NEWS_AND_DOCUMENTS_TEMP =
  'CLEAR_FILTER_NEWS_AND_DOCUMENTS_TEMP';
export const INIT_FILTER_NEWS_AND_DOCUMENTS_TEMP =
  'INIT_FILTER_NEWS_AND_DOCUMENTS_TEMP';
export const SELECT_ALL_MONTH_FILTER_NEWS_AND_DOCUMENTS_TEMP =
  'SELECT_ALL_MONTH_FILTER_NEWS_AND_DOCUMENTS_TEMP';

export const SET_SINGLE_ARTICLE_TYPE = 'SET_SINGLE_ARTICLE_TYPE';
export const SET_SINGLE_ARTICLE = 'SET_SINGLE_ARTICLE';
