import Config from 'react-native-config';

// SVG
import countryVnSvg from '../../assets/svg/country-vn.svg';
import countryUkSvg from '../../assets/svg/country-uk.svg';
import arrowRightSvg from '../../assets/svg/arrow-right.svg';
import arrowLeftSvg from '../../assets/svg/arrow-left.svg';
import arrowDownSvg from '../../assets/svg/arrow-down.svg';
import arrowUpSvg from '../../assets/svg/arrow-up';
import iconErrorSvg from '../../assets/svg/icon-error.svg';
import congratsLeftSvg from '../../assets/svg/congrats-left.svg';
import congratsRightSvg from '../../assets/svg/congrats-right.svg';
import iconCloseSvg from '../../assets/svg/icon-close.svg';
import iconCloseWhiteSvg from '../../assets/svg/close-button-white.svg';
import iconCloseGraySvg from '../../assets/svg/ic_close_gray.svg';
import iconCloseRedSvg from '../../assets/svg/close_red.svg';
import tabbarAccountSvg from '../../assets/svg/tabbar-account.svg';
import tabbarHomeSvg from '../../assets/svg/tabbar-home.svg';
import tabbarNewsActive from '../../assets/svg/tabbar-news-active.png';
import tabbarNewsInactive from '../../assets/svg/tabbar-news-inactive.png';
import tabbarRecognitionActive from '../../assets/svg/tabbar-recognition-active.png';
import tabbarRecognitionInactive from '../../assets/svg/tabbar-recognition-inactive.png';
import tabbarAIACelebrationActive from '../../assets/svg/tabbar-aia-celebration-active.png';
import tabbarAIACelebrationInactive from '../../assets/svg/tabbar-aia-celebration-inactive.png';
import tabbarWellnessActive from '../../assets/svg/tabbar-wellness-active.png';
import tabbarWellnessInactive from '../../assets/svg/tabbar-wellness-inactive.png';
import tabbarWalletActive from '../../assets/svg/tabbar-wallet-active.png';
import tabbarWalletInactive from '../../assets/svg/tabbar-wallet-inactive.png';
import tabbarRecognitionSvg from '../../assets/svg/tabbar-recognition.svg';
import tabbarNewsSvg from '../../assets/svg/tabbar-news.svg';
import tabbarWalletSvg from '../../assets/svg/tabbar-wallet.svg';
import tabbarFlexibleBenefitsSvg from '../../assets/svg/tabbar-flexiblebenefits.svg';
import tabbarVoucherWalletSvg from '../../assets/svg/tabbar-voucher-wallet.svg';
import benefitTabStrokeSvg from '../../assets/svg/benefit-tab-stroke.svg';
import benefitTabSolidSvg from '../../assets/svg/benefit-tab-solid.svg';
import iconHistory from '../../assets/svg/icon-history.svg';
import iconMakeRecognition from '../../assets/svg/icon-make-recognition.svg';
import iconMakeRecognitionNestle from '../../assets/image/nestle/spark.png';
import iconRewards from '../../assets/svg/icon-rewards.svg';
import iconBell from '../../assets/svg/icon-bell.svg';
import iconSearch from '../../assets/svg/icon-search.svg';
import iconCheckActive from '../../assets/svg/icon-check-active.svg';
import iconFail from '../../assets/svg/icon-fail.svg';
import iconCheckNoBorder from '../../assets/svg/icon-check-no-border.js';
import arrowLeft2Svg from '../../assets/svg/arrow-left-2.svg';
import arrowRight2Svg from '../../assets/svg/arrow-right-2.svg';
import iconBack from '../../assets/svg/icon-back.svg';
import iconRatingColCha from '../../assets/svg/rating-colcha-active.svg';
import iconRatingDeter from '../../assets/svg/rating-determine-active.svg';
import iconCaringMentorInactive from '../../assets/svg/AIA-caring-mentor-one-color.svg';
import iconCaringMentorActive from '../../assets/svg/AIA-caring-mentor.svg';
import iconCollaborativeChallengerInactive from '../../assets/svg/AIA-collaborative-challenger-one-color.svg';
import iconCollaborativeChallengerActive from '../../assets/svg/AIA-collaborative-challenger.svg';
import iconCuriousLearnerInactive from '../../assets/svg/AIA-Curious-Learner-one-color.svg';
import iconCuriousLearnerActive from '../../assets/svg/AIA-Curious-Learner.svg';
import iconDeterminedBusinessInactive from '../../assets/svg/AIA-Determined-Business-Driver-one-color.svg';
import iconDeterminedBusinessActive from '../../assets/svg/AIA-Determined-Business-Driver.svg';
import iconForwardThinkingInactive from '../../assets/svg/AIA-forward-thinking-enterpreneur-one-color.svg';
import iconForwardThinkingActive from '../../assets/svg/AIA-forward-thinking-enterpreneur.svg';
import iconInspiringLeaderInactive from '../../assets/svg/AIA-Inspiring-leader-one-color.svg';
import iconInspiringLeaderActive from '../../assets/svg/AIA-Inspiring-leader.svg';
import iconNotiRecognition from '../../assets/svg/iconNotiRecognition.svg';
import iconNotiDeal from '../../assets/svg/iconNotiDeal.svg';
import iconNotiArticle from '../../assets/svg/iconNotiArticle.svg';
import iconCategoryRewardAll from '../../assets/svg/category-reward-all.svg';

import eveBenefitsVN from '../../assets/image/EVE-Benefits-VN.png';
import iconMore from '../../assets/svg/icon-more.svg';
import iconCategoryFlexBenHealthierActive from '../../assets/image/flexible-benefits-healthier-life.png';
import iconCategoryFlexBenHealthierInactive from '../../assets/image/flexible-benefits-healthier-life-gray.png';
import iconCategoryFlexBenLongerActive from '../../assets/image/flexible-benefits-longer-life.png';
import iconCategoryFlexBenLongerInactive from '../../assets/image/flexible-benefits-longer-life-gray.png';
import iconCategoryFlexBenBetterActive from '../../assets/image/flexible-benefits-better-life.png';
import iconCategoryFlexBenBetterInactive from '../../assets/image/flexible-benefits-better-life-gray.png';
import iconHeart from '../../assets/svg/icon-heart.svg';
import iconWedding from '../../assets/svg/icon-wedding.svg';
import iconBirthday from '../../assets/svg/icon-birthday.svg';
import iconParental from '../../assets/svg/icon-parental.svg';
import iconDefaultBenefit from '../../assets/svg/icon-default-benefit.svg';
import iconHealthcarePlan from '../../assets/svg/icon-healthcare-plan.svg';
import iconMedicalCheckUp from '../../assets/svg/icon-medical-check-up.svg';
import iconTrade from '../../assets/svg/icon-trade.svg';
import iconSecurityCheck from '../../assets/svg/icon-security-check.svg';
import iconEVEOffice365 from '../../assets/svg/EVE-Office-365.svg';
import iconGoogle from '../../assets/svg/icon-google.svg';
import closeGreyBackground from '../../assets/svg/close-grey-background';
import sortIcon from '../../assets/svg/sort.svg';
import sortIconIOS from '../../assets/svg/up-down-arrow.svg';
import noResults from '../../assets/svg/depression.svg';
import smile from '../../assets/svg/smile.svg';
import smileColorful from '../../assets/svg/smile-colorful.svg';
import paperPlane from '../../assets/svg/paper-plane.svg';
import flexi4u from '../../assets/image/Flexi4U.png';
import dhlRedChecked from '../../assets/svg/icon-dhl-checked.svg';
import dhlRedBack from '../../assets/svg/icon-dhl-red-back.svg';
import dhlCheckSvg from '../../assets/svg/icon-svg-dhl-check.svg';
import athenaCheckSvg from '../../assets/svg/athena_check_box.svg';
import svgTopUp from '../../assets/svg/svg-top-up.svg';
import iconScanMe from '../../assets/svg/icon-scan-me.svg';
import iconScanQr from '../../assets/svg/icon-scan-qr.svg';
import iconMyQR from '../../assets/svg/icon-my-qrcode.svg';
import iconScanQrGray from '../../assets/svg/icon-scan-qr-gray.svg';
import iconMyQRGray from '../../assets/svg/icon-my-qrcode-gray.svg';
import recognition from '../../assets/svg/recognition.svg';
import upLoadFile from '../../assets/svg/upload.svg';
import close from '../../assets/svg/close.svg';
import fileDefault from '../../assets/svg/file.svg';
import athenaBenefitsSvg from '../../assets/svg/athena-benefits.svg';
import pepsiHomeBackgroud from '../../assets/image/pepsi/home-background.png';
import iconActivityLog from '../../assets/svg/icon-receipt.svg';
import iconScreenshot from '../../assets/svg/icon-screenshot.svg';
import iconUp from '../../assets/svg/icon-up.svg';
import iconDown from '../../assets/svg/icon-down.svg';
import iconWalletHistory from '../../assets/svg/icon-wallet-history.svg';
import iconPepsiChecked from '../../assets/svg/icon-pepsi-checked.svg';
import iconPepsiCheckedForce from '../../assets/svg/icon-pepsi-checked-force.svg';
import iconRemove from '../../assets/svg/icon-remove.svg';
import iconAdd from '../../assets/svg/icon-add.svg';
import iconCircleSelected from '../../assets/svg/icon-circle-selected.svg';
import iconFilter from '../../assets/svg/icon-filter.svg';
// Splash page
export const SPLASH_IMAGE = require('../../assets/splash-logo.png');
// Welcome
export const SVG_COUNTRY_VN = countryVnSvg;
export const SVG_COUNTRY_UK = countryUkSvg;
export const SVG_OFFICE_365 = iconEVEOffice365;
export const SVG_GOOGLE = iconGoogle;
// Common
export const SVG_ARROW_RIGHT = arrowRightSvg;
export const SVG_ARROW_LEFT = arrowLeftSvg;
export const SVG_ARROW_DOWN = arrowDownSvg;
export const SVG_ARROW_UP = arrowUpSvg;
export const SVG_ICON_ERROR = iconErrorSvg;
export const SVG_CONGRATS_LEFT = congratsLeftSvg;
export const SVG_CONGRATS_RIGHT = congratsRightSvg;
export const SVG_ICON_CLOSE = iconCloseSvg;
export const SVG_ICON_CLOSE_GRAY = iconCloseGraySvg;
export const SVG_ICON_CLOSE_RED = iconCloseRedSvg;
export const SVG_ICON_CLOSE_WHITE = iconCloseWhiteSvg;
export const SVG_TABBAR_HOME = tabbarHomeSvg;
export const TABBAR_NEWS_ACTIVE = tabbarNewsActive;
export const TABBAR_NEWS_INACTIVE = tabbarNewsInactive;
export const TABBAR_RECOGNITION_ACTIVE = tabbarRecognitionActive;
export const TABBAR_RECOGNITION_INACTIVE = tabbarRecognitionInactive;
export const TABBAR_AIACelebration_ACTIVE = tabbarAIACelebrationActive;
export const TABBAR_AIACelebration_INACTIVE = tabbarAIACelebrationInactive;
export const TABBAR_WELLNESS_ACTIVE = tabbarWellnessActive;
export const TABBAR_WELLNESS_INACTIVE = tabbarWellnessInactive;
export const TABBAR_WALLET_ACTIVE = tabbarWalletActive;
export const TABBAR_WALLET_INACTIVE = tabbarWalletInactive;
export const SVG_TABBAR_ACCOUNT = tabbarAccountSvg;
export const SVG_TABBAR_RECOGNITION = tabbarRecognitionSvg;
export const SVG_TABBAR_NEWS = tabbarNewsSvg;
export const SVG_TABBAR_WALLET = tabbarWalletSvg;
export const SVG_TABBAR_FLEXIBLE_BENEFITS = tabbarFlexibleBenefitsSvg;
export const SVG_TABBAR_VOUCHER_WALLET = tabbarVoucherWalletSvg;
export const SVG_BENEFIT_TAB_STROKE = benefitTabStrokeSvg;
export const SVG_BENEFIT_TAB_SOLID = benefitTabSolidSvg;
export const SVG_ICON_HISTORY = iconHistory;
export const SVG_ICON_REWARDS = iconRewards;
export const SVG_ICON_MAKE_RECOGNITION = iconMakeRecognition;
export const SVG_ICON_MAKE_RECOGNITION_NESTLE = iconMakeRecognitionNestle;
export const SVG_ICON_BELL = iconBell;
export const SVG_ICON_SEARCH = iconSearch;
export const AVATAR_MALE = require('../../assets/avatar-male.png');
export const SVG_ICON_CHECK_ACTIVE = iconCheckActive;
export const SVG_ICON_FAIL = iconFail;
export const SVG_ICON_CHECK_NO_BORDER = iconCheckNoBorder;
export const SVG_ARROW_LEFT_2 = arrowLeft2Svg;
export const SVG_ARROW_RIGHT_2 = arrowRight2Svg;
export const SVG_ICON_BACK = iconBack;
export const SVG_ICON_RATING_COLCHA = iconRatingColCha;
export const SVG_ICON_RATING_DETER = iconRatingDeter;
export const PLACEHOLDER_IMAGE = require('../../assets/placeholder.jpg');
export const SVG_ICON_CATEGORY_REWARD_ALL = iconCategoryRewardAll;
export const SVG_ICON_MORE = iconMore;
export const SVG_ICON_HEART = iconHeart;
export const SVG_ICON_TRADE = iconTrade;
export const SVG_ICON_SECURITY_CHECK = iconSecurityCheck;
export const SVG_RECOGNITION = recognition;
export const SVG_UPLOAD = upLoadFile;
export const SVG_CLOSE = close;
export const SVG_FILE = fileDefault;
export const SVG_ACTIVITY_LOG = iconActivityLog;
export const SVG_ICON_SCREENSHOT = iconScreenshot;
export const SVG_ICON_UP = iconUp;
export const SVG_ICON_DOWN = iconDown;
export const SVG_ICON_REMOVE = iconRemove;
export const SVG_ICON_ADD = iconAdd;
export const SVG_ICON_CIRCLE_SELECTED = iconCircleSelected;
export const SVG_ICON_FILTER = iconFilter;
//RATING CRITERIA
export const SVG_ICON_CARING_MENTOR_ACTIVE = iconCaringMentorActive;
export const SVG_ICON_CARING_MENTOR_INACTIVE = iconCaringMentorInactive;
export const SVG_ICON_COLLABORATIVE_CHALLENGER_ACTIVE = iconCollaborativeChallengerActive;
export const SVG_ICON_COLLABORATIVE_CHALLENGER_INACTIVE = iconCollaborativeChallengerInactive;
export const SVG_ICON_CURIOUS_LEARNER_ACTIVE = iconCuriousLearnerActive;
export const SVG_ICON_CURIOUS_LEARNER_INACTIVE = iconCuriousLearnerInactive;
export const SVG_ICON_DETERMINED_BUSINESS_ACTIVE = iconDeterminedBusinessActive;
export const SVG_ICON_DETERMINED_BUSINESS_INACTIVE = iconDeterminedBusinessInactive;
export const SVG_ICON_FORWARD_THINKING_ACTIVE = iconForwardThinkingActive;
export const SVG_ICON_FORWARD_THINKING_INACTIVE = iconForwardThinkingInactive;
export const SVG_ICON_INSPIRING_LEADER_ACTIVE = iconInspiringLeaderActive;
export const SVG_ICON_INSPIRING_LEADER_INACTIVE = iconInspiringLeaderInactive;
export const SVG_ICON_NOTI_ARTICLE = iconNotiArticle;
export const SVG_ICON_NOTI_DEAL = iconNotiDeal;
export const SVG_ICON_NOTI_RECOGNITION = iconNotiRecognition;
export const EVE_BENEFITS_VN = eveBenefitsVN;
//FLEXIBLE-BENEFITS
export const PNG_ICON_FLEX_BEN_HEALTHIER_ACTIVE = iconCategoryFlexBenHealthierActive;
export const PNG_ICON_FLEX_BEN_HEALTHIER_INACTIVE = iconCategoryFlexBenHealthierInactive;
export const PNG_ICON_FLEX_BEN_LONGER_ACTIVE = iconCategoryFlexBenLongerActive;
export const PNG_ICON_FLEX_BEN_LONGER_INACTIVE = iconCategoryFlexBenLongerInactive;
export const PNG_ICON_FLEX_BEN_BETTER_ACTIVE = iconCategoryFlexBenBetterActive;
export const PNG_ICON_FLEX_BEN_BETTER_INACTIVE = iconCategoryFlexBenBetterInactive;
export const SVG_ICON_WEDDING = iconWedding;
export const SVG_ICON_BIRTHDAY = iconBirthday;
export const SVG_ICON_PARENTAL = iconParental;
export const SVG_ICON_DEFAULT_BENEFIT = iconDefaultBenefit;
export const SVG_ICON_HEALTHCARE_PLAN = iconHealthcarePlan;
export const SVG_ICON_MEDICAL_CHECK_UP = iconMedicalCheckUp;
export const PNG_FLEXI4U = flexi4u;
export const SVG_ATHENA_BENEFITS = athenaBenefitsSvg;

//News and documents
export const SWIPER_1_IMAGE = require('../../assets/image/swiper-1.png');
export const SWIPER_2_IMAGE = require('../../assets/image/swiper-2.png');
export const SWIPER_3_IMAGE = require('../../assets/image/swiper-3.png');

// FlexA
export const FLEXA_WHITE = require('../../assets/image/FlexA-White.png');
export const FLEXA_GRAY = require('../../assets/image/FlexA-Gray.png');
export const FLEXA_GRAY_DARK = require('../../assets/image/FlexA.png');
export const FLEXA = require('../../assets/image/FlexA.png');

//Rating
export const RATING = require('../../assets/image/ic_rating.png');
export const RATING_SUCCESS = require('../../assets/image/ic_rating_success.png');
export const NEW_REWARD = require('../../assets/image/ic_new_reward.png');

// Sort
export const SVG_SORT = sortIcon;
export const SVG_SORT_IOS = sortIconIOS;
export const CLOSE_GREY_BACKGROUND = closeGreyBackground;
export const SVG_NO_RESULTS = noResults;
export const SVG_SMILE = smile;
export const SVG_PAPER_PLANE = paperPlane;
export const SVG_SMILE_COLORFUL = smileColorful;
export const SVG_DHL_RED_CHECKED = dhlRedChecked;
export const SVG_DHL_RED_BACK = dhlRedBack;
export const SVG_DHL_CHECK = dhlCheckSvg;
export const SVG_ATHENA_CHECK = athenaCheckSvg;
export const SVG_TOP_UP = svgTopUp;
export const DHL_HOME_IMAGE = { uri: `${Config.CDN_URL}/images/home_header.png` };
export const PEPSI_HOME_IMAGE = pepsiHomeBackgroud;

// Profile
export const ICON_SCAN_ME = iconScanMe;
export const ICON_MY_QR = iconMyQR;
export const ICON_SCAN_QR = iconScanQr;
export const ICON_MY_QR_GRAY = iconMyQRGray;
export const ICON_SCAN_QR_GRAY = iconScanQrGray;
export const ICON_WALLET_HISTORY = iconWalletHistory;
export const ICON_PEPSI_CHECKED = iconPepsiChecked;
export const ICON_PEPSI_CHECKED_FORCE = iconPepsiCheckedForce;
export const QR_CODE_READING = require('../../assets/image/qrcode-reading.png');
export const USER_INFO_COVER = require('../../assets/image/user-info-cover.png');
