//WELCOME
export const TITLE_WELCOME = 'TITLE_WELCOME';
export const LABEL_SELECT_LANGUAGE = 'LABEL_SELECT_LANGUAGE';
export const BUTTON_ENGLISH = 'BUTTON_ENGLISH';
export const BUTTON_VIETNAMESE = 'BUTTON_VIETNAMESE';
export const TITLE_GET_STARTED = 'TITLE_GET_STARTED';
//LOGIN
export const TITLE_WELCOME_BACK = 'TITLE_WELCOME_BACK';
export const LABEL_NOT_HAVE_ACCOUNT = 'LABEL_NOT_HAVE_ACCOUNT';
export const BUTTON_SIGN_IN = 'BUTTON_SIGN_IN';
export const BUTTON_SIGN_IN_WITH_NESTLE = 'BUTTON_SIGN_IN_WITH_NESTLE';
export const BUTTON_SIGN_IN_WITH_OFFICE365 = 'BUTTON_SIGN_IN_WITH_OFFICE365';
export const BUTTON_SIGN_IN_WITH_GOOGLE = 'BUTTON_SIGN_IN_WITH_GOOGLE';
export const BUTTON_SIGN_IN_WITH_FACEID = 'BUTTON_SIGN_IN_WITH_FACEID';
export const BUTTON_SIGN_IN_WITH_FINGERPRINT = 'BUTTON_SIGN_IN_WITH_FINGERPRINT';
export const BUTTON_FORGOT_PASSWORD = 'BUTTON_FORGOT_PASSWORD';
export const BUTTON_REGISTER = 'BUTTON_REGISTER';
export const LABEL_PASSWORD_MUST_BE_CHANGE = 'LABEL_PASSWORD_MUST_BE_CHANGE';
export const LABEL_TITLE_PASSWORD_CHANGE = 'LABEL_TITLE_PASSWORD_CHANGE';
//REGISTER
export const TITLE_LEARN_MORE_ABOUT_USERNAME_RULE =
  'TITLE_LEARN_MORE_ABOUT_USERNAME_RULE';
export const TITLE_REGISTER = 'TITLE_REGISTER';
export const FIELD_USERNAME_LABEL = 'FIELD_USERNAME_LABEL';
export const FIELD_EMPLOYEE_ID = 'FIELD_EMPLOYEE_ID';
export const FIELD_USERNAME_PLACEHOLDER = 'FIELD_USERNAME_PLACEHOLDER';
export const FIELD_PASSWORD_LABEL = 'FIELD_PASSWORD_LABEL';
export const FIELD_PASSWORD_PLACEHOLDER = 'FIELD_PASSWORD_PLACEHOLDER';
export const FIELD_CONFIRM_PASSWORD_LABEL = 'FIELD_CONFIRM_PASSWORD_LABEL';
export const FIELD_CONFIRM_PASSWORD_PLACEHOLDER =
  'FIELD_CONFIRM_PASSWORD_PLACEHOLDER';
export const LABEL_HAVE_ACCOUNT = 'LABEL_HAVE_ACCOUNT';
export const FIELD_PASSWORD_REQUIRED = 'FIELD_PASSWORD_REQUIRED';
export const FIELD_USERNAME_REQUIRED = 'FIELD_USERNAME_REQUIRED';
export const FIELD_USERNAME_CAN_NOT_REGISTER =
  'FIELD_USERNAME_CAN_NOT_REGISTER';
export const FIELD_CONFIRM_PASSWORD_MATCH = 'FIELD_CONFIRM_PASSWORD_MATCH';
//SECURITY_QUESTION
export const TITLE_SECURITY_QUESTION = 'TITLE_SECURITY_QUESTION';
export const FIELD_FIRST_SECURITY_QUESTION_LABEL =
  'FIELD_FIRST_SECURITY_QUESTION_LABEL';
export const FIELD_FIRST_SECURITY_QUESTION_PLACEHOLDER =
  'FIELD_FIRST_SECURITY_QUESTION_PLACEHOLDER';
export const FIELD_FIRST_SECURITY_QUESTION_REQUIRED =
  'FIELD_FIRST_SECURITY_QUESTION_REQUIRED';
export const FIELD_SECOND_SECURITY_QUESTION_LABEL =
  'FIELD_SECOND_SECURITY_QUESTION_LABEL';
export const FIELD_SECOND_SECURITY_QUESTION_PLACEHOLDER =
  'FIELD_SECOND_SECURITY_QUESTION_PLACEHOLDER';
export const FIELD_SECOND_SECURITY_QUESTION_REQUIRED =
  'FIELD_SECOND_SECURITY_QUESTION_REQUIRED';
export const FIELD_FIRST_ANSWER_LABEL = 'FIELD_FIRST_ANSWER_LABEL';
export const FIELD_FIRST_ANSWER_PLACEHOLDER = 'FIELD_FIRST_ANSWER_PLACEHOLDER';
export const FIELD_FIRST_ANSWER_REQUIRED = 'FIELD_FIRST_ANSWER_REQUIRED';
export const FIELD_SECOND_ANSWER_LABEL = 'FIELD_SECOND_ANSWER_LABEL';
export const FIELD_SECOND_ANSWER_PLACEHOLDER =
  'FIELD_SECOND_ANSWER_PLACEHOLDER';
export const FIELD_SECOND_ANSWER_REQUIRED = 'FIELD_SECOND_ANSWER_REQUIRED';
export const FIELD_QUESTIONS_MUST_NOT_MATCH = 'FIELD_QUESTIONS_MUST_NOT_MATCH';
export const MODAL_TITLE_USERNAME = 'MODAL_TITLE_USERNAME';
export const MODAL_DESCRIPTION_USERNAME = 'MODAL_DESCRIPTION_USERNAME';
export const MODAL_DESCRIPTION_HIGHLIGHT_USERNAME =
  'MODAL_DESCRIPTION_HIGHLIGHT_USERNAME';
export const BUTTON_GOT_IT = 'BUTTON_GOT_IT';
// UPLOAD AVATAR
export const TITLE_UPLOAD_AVATAR = 'TITLE_UPLOAD_AVATAR';
export const FIELD_DESCRIPTION_UPLOAD_AVATAR =
  'FIELD_DESCRIPTION_UPLOAD_AVATAR';
export const BUTTON_TAKE_PHOTO = 'BUTTON_TAKE_PHOTO';
export const BUTTON_CHOOSE_FROM_LIBRARY = 'BUTTON_CHOOSE_FROM_LIBRARY';
export const FIELD_UPLOAD_AVATAR_EMPTY = 'FIELD_UPLOAD_AVATAR_EMPTY';
//CONFIRMATION
export const TITLE_CONFIRMATION = 'TITLE_CONFIRMATION';
//REGISTER-SUCCESS
export const TITLE_CONGRATS = 'TITLE_CONGRATS';
export const SUBTITLE_REGISTER_SUCCESS = 'SUBTITLE_REGISTER_SUCCESS';
export const BUTTON_SIGN_IN_NOW = 'BUTTON_SIGN_IN_NOW';
//FORGOT_PASSWORD
export const TITLE_FORGOT_PASSWORD = 'TITLE_FORGOT_PASSWORD';
export const SUBTITLE_FORGOT_PASSWORD = 'SUBTITLE_FORGOT_PASSWORD';
export const FIELD_NEW_PASSWORD_LABEL = 'FIELD_NEW_PASSWORD_LABEL';
export const FIELD_NEW_PASSWORD_PLACEHOLDER = 'FIELD_NEW_PASSWORD_PLACEHOLDER';
export const FIELD_NEW_PASSWORD_REQUIRED = 'FIELD_NEW_PASSWORD_REQUIRED';
export const FIELD_NEW_PASSWORD_INVALID = 'FIELD_NEW_PASSWORD_INVALID';
export const FIELD_USERNAME_CAN_NOT_RESET_PASSWORD = 'FIELD_USERNAME_CAN_NOT_RESET_PASSWORD';
export const VERIFY_FORGOT_PASSWORD_TITLE = 'VERIFY_FORGOT_PASSWORD_TITLE';
export const VERIFY_FORGOT_PASSWORD_DESC = 'VERIFY_FORGOT_PASSWORD_DESC';
export const BTN_VERIFY = 'BTN_VERIFY';
export const BTN_RESEND = 'BTN_RESEND';
export const BLANK_VERIFY_CODE = 'BLANK_VERIFY_CODE';
export const RENEW_VERIFY_CODE_COUNTDOWN = 'RENEW_VERIFY_CODE_COUNTDOWN';
export const RENEW_VERIFY_CODE_QUESTION = 'RENEW_VERIFY_CODE_QUESTION';
export const LABEL_FORGOT_PASSWORD = 'LABEL_FORGOT_PASSWORD';
export const BTN_FORGOT_PASSWORD = 'BTN_FORGOT_PASSWORD';
//RESET_PASSWORD
export const TITLE_RESET_PASSWORD = 'TITLE_RESET_PASSWORD';
export const SUBTITLE_RESET_PASSWORD_SUCCESS = 'SUBTITLE_RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_SUCCESS_DESC = 'RESET_PASSWORD_SUCCESS_DESC';
export const RESET_PASSWORD_AND_AUTO_LOGIN_SUCCESS_DESC = 'RESET_PASSWORD_AND_AUTO_LOGIN_SUCCESS_DESC';
//RECOGNITION
export const TITLE_CURRENT_BALANCE = 'TITLE_CURRENT_BALANCE';
export const TITLE_MAKE_A_RECOGNITION = 'TITLE_MAKE_A_RECOGNITION';
export const TITLE_MY_REWARDS = 'TITLE_MY_REWARDS';
export const TITLE_COMING_SOON = 'TITLE_COMING_SOON';
export const CONTENT_COMING_SOON = 'CONTENT_COMING_SOON';
export const TITLE_HISTORY = 'TITLE_HISTORY';
export const TITLE_RECOGNITION_POINTS = 'TITLE_RECOGNITION_POINTS';
export const TITLE_RECOGNITION_POINT = 'TITLE_RECOGNITION_POINT';
export const TITLE_RECOGNITION_POINTS_FOR_NOTIFICATION =
  'TITLE_RECOGNITION_POINTS_FOR_NOTIFICATION';
export const TITLE_RECOGNITION_POINTS_NEW = 'TITLE_RECOGNITION_POINTS_NEW';
export const TITLE_SENT_RECOGNITION_POINTS = 'TITLE_SENT_RECOGNITION_POINTS';
export const TITLE_REWARD_COINS = 'TITLE_REWARD_COINS';
export const TITLE_RECEIVED_RECOGNITIONS = 'TITLE_RECEIVED_RECOGNITIONS';
export const LABEL_POINTS = 'LABEL_POINTS';
export const LABEL_GIVE_POINT = 'LABEL_GIVE_POINT';
export const LABEL_POINT = 'LABEL_POINT';
export const LABEL_COINS = 'LABEL_COINS';
export const LABEL_COIN = 'LABEL_COIN';
export const LABEL_KUDOS = 'LABEL_KUDOS';
export const LABEL_FLEX_POINTS = 'LABEL_FLEX_POINTS';
export const LABEL_FLEX_POINT = 'LABEL_FLEX_POINT';
export const LABEL_FLEX_POINTS_FOR_NOTIFICATION =
  'LABEL_FLEX_POINTS_FOR_NOTIFICATION';
export const TITLE_RECOGNITION = 'TITLE_RECOGNITION';
export const BUTTON_LEARN_MORE_RECOGNITION = 'BUTTON_LEARN_MORE_RECOGNITION';
export const FIELD_SEARCH_NAME_PLACEHOLDER = 'FIELD_SEARCH_NAME_PLACEHOLDER';
export const FIELD_SEARCH_REWARD_PLACEHOLDER =
  'FIELD_SEARCH_REWARD_PLACEHOLDER';
export const LABEL_GIVING_RECOGNITION_POINT = 'LABEL_GIVING_RECOGNITION_POINT';
export const LABEL_GIVING_RECOGNITION_DESCRIPTION =
  'LABEL_GIVING_RECOGNITION_DESCRIPTION';
export const FIELD_WRITE_NOTE_PLACEHOLDER = 'FIELD_WRITE_NOTE_PLACEHOLDER';
export const LABEL_SELECT_KUDOS_SOURCE = 'LABEL_SELECT_KUDOS_SOURCE';
export const LABEL_RATING_VALUE_CRITERIA = 'LABEL_RATING_VALUE_CRITERIA';
export const FIELD_RECEIVER_REQUIRED = 'FIELD_RECEIVER_REQUIRED';
export const FIELD_CRITERIA_REQUIRED = 'FIELD_CRITERIA_REQUIRED';
export const FIELD_SEFT_RECONGINATION_SCHEME_REQUIED =
  'FIELD_SEFT_RECONGINATION_SCHEME_REQUIED';
export const FIELD_NOTE_REQUIRED = 'FIELD_NOTE_REQUIRED';
export const FIELD_NOTE_MINIMUM_WORDS_REQUIRED =
  'FIELD_NOTE_MINIMUM_WORDS_REQUIRED';
export const MODAL_DESCRIPTION_SEND_RECOGNITION =
  'MODAL_DESCRIPTION_SEND_RECOGNITION';
export const MODAL_DESCRIPTION_SEND_RECOGNITION_SMALLER =
  'MODAL_DESCRIPTION_SEND_RECOGNITION_SMALLER';
export const MODAL_DESCRIPTION_SEND_RECOGNITION_ZERO =
  'MODAL_DESCRIPTION_SEND_RECOGNITION_ZERO';
export const TITLE_SEND_RECOGNITION_SUCCESS = 'TITLE_SEND_RECOGNITION_SUCCESS';
export const DESCRIPTION_SEND_RECOGNITION_SUCCESS = 'DESCRIPTION_SEND_RECOGNITION_SUCCESS';
export const COUNT_NOTIFIED_SEND_RECOGNITION_SUCCESS = 'COUNT_NOTIFIED_SEND_RECOGNITION_SUCCESS';
export const DESCRIPTION_SEND_RECOGNITION_SUCCESS_EXPIRED =
  'DESCRIPTION_SEND_RECOGNITION_SUCCESS_EXPIRED';
export const TITLE_SEND_RECOGNITION_SUCCESS_FOR_DHL =
  'TITLE_SEND_RECOGNITION_SUCCESS_FOR_DHL';
export const DESCRIPTION_SEND_RECOGNITION_SUCCESS_FOR_DHL =
  'DESCRIPTION_SEND_RECOGNITION_SUCCESS_FOR_DHL';
export const LABEL_BRANCH = 'LABEL_BRANCH';
export const TITLE_LOCATION = 'TITLE_LOCATION';
export const LABEL_USED_THIS_WEEK = 'LABEL_USED_THIS_WEEK';
export const LABEL_USED_TO_DAY = 'LABEL_USED_TO_DAY';
export const LABEL_RECEIVED = 'LABEL_RECEIVED';
export const LABEL_USED = 'LABEL_USED';
export const LABEL_LISTS = 'LABEL_LISTS';
export const LABEL_SEND = 'LABEL_SEND';
export const TITLE_TIME = 'TITLE_TIME';
export const BUTTON_ALL_MONTHS = 'BUTTON_ALL_MONTHS';
export const LABEL_THE_LATEST = 'LABEL_THE_LATEST';
export const LABEL_THE_NEW = 'LABEL_THE_NEW';
export const LABEL_THE_OLDEST = 'LABEL_THE_OLDEST';
export const TITLE_FLEXBEN_BUDGET = 'TITLE_FLEXBEN_BUDGET';
export const LABEL_EXPIRY_DAY = 'LABEL_EXPIRY_DAY';
export const LABEL_RECOGNITION_WARNING_MESSAGE =
  'LABEL_RECOGNITION_WARNING_MESSAGE';
export const LABEL_PUBLIC_RECOGNITION_TITLE = 'LABEL_PUBLIC_RECOGNITION_TITLE';
export const LABEL_PUBLIC_RECOGNITION_DESCRIPTION =
  'LABEL_PUBLIC_RECOGNITION_DESCRIPTION';
export const LABEL_PUBLICIZE_RECOGNITION = 'LABEL_PUBLICIZE_RECOGNITION';
export const LABEL_PUBLICIZE_RECOGNITION_DESCRIPTION =
  'LABEL_PUBLICIZE_RECOGNITION_DESCRIPTION';
export const TITLE_RECOGNITION_NOTIFY_TO = 'TITLE_RECOGNITION_NOTIFY_TO';
export const TITLE_RECOGNITION_NOTIFY_TO_DESC =
  'TITLE_RECOGNITION_NOTIFY_TO_DESC';
export const LABEL_ADD_RECEIVER = 'LABEL_ADD_RECEIVER';
export const LABEL_ADD_MORE = 'LABEL_ADD_MORE';
export const LABEL_OTHERS = 'LABEL_OTHERS';
export const LABEL_GROUP_KUDOS = 'LABEL_GROUP_KUDOS';
export const LABEL_GROUP_KUDOS_EQUALLY_ALLOCATE =
  'LABEL_GROUP_KUDOS_EQUALLY_ALLOCATE';
export const LABEL_GROUP_KUDOS_CUSTOM_ALLOCATE =
  'LABEL_GROUP_KUDOS_CUSTOM_ALLOCATE';
export const LABEL_GROUP_KUDOS_SELECT_GROUP = 'LABEL_GROUP_KUDOS_SELECT_GROUP';
export const LABEL_GROUP_KUDOS_PARTICIPANTS = 'LABEL_GROUP_KUDOS_PARTICIPANTS';
export const LABEL_GROUP_KUDOS_NOTE = 'LABEL_GROUP_KUDOS_NOTE';
export const LABEL_RECOGNITION_HISTORY = 'LABEL_RECOGNITION_HISTORY';
export const CODE_COPIED_TO_CLIPBOARD = 'CODE_COPIED_TO_CLIPBOARD';

//SINGLE
export const TITLE_ACTION_RECORDS = 'TITLE_ACTION_RECORDS';
export const LABEL_DEPARTMENT_PREFIX = 'LABEL_DEPARTMENT_PREFIX';
export const LABEL_LOCATION_PREFIX = 'LABEL_LOCATION_PREFIX';
export const LABEL_TIME_PREFIX = 'LABEL_TIME_PREFIX';
export const LABEL_GIVEN = 'LABEL_GIVEN';
export const LABEL_RECEIVED_POINT = 'LABEL_RECEIVED_POINT';
export const LABEL_MESSAGE = 'LABEL_MESSAGE';
//NEWS-AND-DOCUMENTS
export const TITLE_NEWS_AND_DOCUMENTS = 'TITLE_NEWS_AND_DOCUMENTS';
export const LABEL_NEWS = 'LABEL_NEWS';
export const LABEL_DOCUMENTS = 'LABEL_DOCUMENTS';
//NOTIFICATIONS
export const TIME_TODAY_FORMAT = 'TIME_TODAY_FORMAT';
export const TIME_YESTERDAY_FORMAT = 'TIME_YESTERDAY_FORMAT';
export const TITLE_NOTIFICATIONS = 'TITLE_NOTIFICATIONS';
export const BUTTON_CLEAR_ALL = 'BUTTON_CLEAR_ALL';
export const BUTTON_READ_ALL = 'BUTTON_READ_ALL';
export const LABEL_RECOGNITION_RECEIVED_NOTIFICATION =
  'LABEL_RECOGNITION_RECEIVED_NOTIFICATION';
export const LABEL_RECOGNITION_RECEIVED_NOTIFICATION_FOR_PEPSI =
  'LABEL_RECOGNITION_RECEIVED_NOTIFICATION_FOR_PEPSI';
export const LABEL_RECOGNITION_RECEIVED_NOTIFICATION_FOR_NOTIFY_USER_MANAGER =
  'LABEL_RECOGNITION_RECEIVED_NOTIFICATION_FOR_NOTIFY_USER_MANAGER';
export const LABEL_RECOGNITION_RECALL_NOTIFICATION =
  'LABEL_RECOGNITION_RECALL_NOTIFICATION';
export const BUTTON_RECALL = 'BUTTON_RECALL';
export const MODAL_TITLE_CONFIRM_RECALL_RECOGNITION =
  'MODAL_TITLE_CONFIRM_RECALL_RECOGNITION';
export const MODAL_DESCRIPTION_CONFIRM_RECALL_RECOGNITION =
  'MODAL_DESCRIPTION_CONFIRM_RECALL_RECOGNITION';
export const MODAL_TITLE_SUCCESS_RECALL_RECOGNITION =
  'MODAL_TITLE_SUCCESS_RECALL_RECOGNITION';
export const MODAL_TITLE_FAIL_RECALL_RECOGNITION =
  'MODAL_TITLE_FAIL_RECALL_RECOGNITION';
export const MODAL_DESCRIPTION_SUCCESS_RECALL_RECOGNITION =
  'MODAL_DESCRIPTION_SUCCESS_RECALL_RECOGNITION';
export const MODAL_DESCRIPTION_SUCCESS_RECALL_RECOGNITION_PART =
  'MODAL_DESCRIPTION_SUCCESS_RECALL_RECOGNITION_PART';
export const MODAL_DESCRIPTION_FAIL_RECALL_RECOGNITION =
  'MODAL_DESCRIPTION_FAIL_RECALL_RECOGNITION';
export const LABEL_FLEXIBLE_BENEFITS_RECEIVED_NOTIFICATION =
  'LABEL_FLEXIBLE_BENEFITS_RECEIVED_NOTIFICATION';
export const LABEL_ARTICLE_NOTIFICATION = 'LABEL_ARTICLE_NOTIFICATION';
export const LABEL_DOCUMENTS_NOTIFICATION = 'LABEL_DOCUMENTS_NOTIFICATION';
export const LABEL_HOT_DEAL_NOTIFICATION = 'LABEL_HOT_DEAL_NOTIFICATION';
export const LABEL_QUARTERLY_RECOGNITION_NOTIFICATION =
  'LABEL_QUARTERLY_RECOGNITION_NOTIFICATION';
export const LABEL_QUARTERLY_RECOGNITION_COMMENT_NOTIFICATION =
  'LABEL_QUARTERLY_RECOGNITION_COMMENT_NOTIFICATION';
export const LABEL_SUBMIT_ALL_QUARTERLY_RECOGNITION_NOTIFICATION =
  'LABEL_SUBMIT_ALL_QUARTERLY_RECOGNITION_NOTIFICATION';
export const LABEL_APPROVED_OR_REJECTED_QUARTERLY_RECOGNITION_NOTIFICATION =
  'LABEL_APPROVED_OR_REJECTED_QUARTERLY_RECOGNITION_NOTIFICATION';
export const LABEL_REJECTED = 'LABEL_REJECTED';
export const LABEL_APPROVED = 'LABEL_APPROVED';
export const LABEL_SENDER_RECOMMENDED_NOTIFICATION =
  'LABEL_SENDER_RECOMMENDED_NOTIFICATION';
export const LABEL_NON_VOUCHER_NOTIFICATION = 'LABEL_NON_VOUCHER_NOTIFICATION';
export const LABEL_NON_VOUCHER_NOTIFICATION_FAILED =
  'LABEL_NON_VOUCHER_NOTIFICATION_FAILED';
export const LABEL_VOUCHER_NOTIFICATION_FAILED =
  'LABEL_VOUCHER_NOTIFICATION_FAILED';
export const LABEL_REGCONITION = 'LABEL_REGCONITION';
export const LABEL_REGCONITIONS = 'LABEL_REGCONITIONS';
export const LABEL_REGCONITION_APPROVED = 'LABEL_REGCONITION_APPROVED';
export const LABEL_REGCONITION_REJECT = 'LABEL_REGCONITION_REJECT';
export const LABEL_ADMIN_REVIEW_RECOGNITION_NOTIFICATION =
  'LABEL_ADMIN_REVIEW_RECOGNITION_NOTIFICATION';
export const LABEL_ADMIN_REVIEW_RECOGNITIONS_NOTIFICATION =
  'LABEL_ADMIN_REVIEW_RECOGNITIONS_NOTIFICATION';
export const LABEL_ADMIN_REVIEW_RECOGNITION_NOTIFICATION_SELF =
  'LABEL_ADMIN_REVIEW_RECOGNITION_NOTIFICATION_SELF';
export const LABEL_ADMIN_REVIEW_RECOGNITIONS_NOTIFICATION_SELF =
  'LABEL_ADMIN_REVIEW_RECOGNITIONS_NOTIFICATION_SELF';
export const LABEL_MANAGED_EMPLOYEE_BEEN_RECOGNISED_NOTIFICATION =
  'LABEL_MANAGED_EMPLOYEE_BEEN_RECOGNISED_NOTIFICATION';
export const LABEL_MANAGED_EMPLOYEE_BEEN_RECOGNISED_NOTIFICATION_SELF =
  'LABEL_MANAGED_EMPLOYEE_BEEN_RECOGNISED_NOTIFICATION_SELF';
export const LABEL_RECEIVED_RECOGNITION_PROGRAM_NOTIFICATION =
  'LABEL_RECEIVED_RECOGNITION_PROGRAM_NOTIFICATION';
export const LABEL_REPLY_RECOGNITION_NOTIFICATION =
  'LABEL_REPLY_RECOGNITION_NOTIFICATION';
export const NOTIFICATION_TAB_RECOGNITIONS = 'NOTIFICATION_TAB_RECOGNITIONS';
export const NOTIFICATION_TAB_NEWS = 'NOTIFICATION_TAB_NEWS';
export const NOTIFICATION_TAB_QUARTERLY = 'NOTIFICATION_TAB_QUARTERLY';
export const NOTIFICATION_TAB_SURVEYS = 'NOTIFICATION_TAB_SURVEYS';
export const NOTIFICATION_TAB_BENEFITS = 'NOTIFICATION_TAB_BENEFITS';

//REWARD
export const LABEL_REWARD_CATEGORY = 'LABEL_REWARD_CATEGORY';
export const LABEL_REWARD_CATEGORY_ALL = 'LABEL_REWARD_CATEGORY_ALL';
export const LABEL_REWARD_CATEGORY_FOOD = 'LABEL_REWARD_CATEGORY_FOOD';
export const LABEL_REWARD_CATEGORY_BEVERAGE = 'LABEL_REWARD_CATEGORY_BEVERAGE';
export const LABEL_REWARD_CATEGORY_ENTERTAINMENT =
  'LABEL_REWARD_CATEGORY_ENTERTAINMENT';
export const LABEL_REWARD_CATEGORY_SHOPPING = 'LABEL_REWARD_CATEGORY_SHOPPING';
export const LABEL_REWARD_CATEGORY_BILLS = 'LABEL_REWARD_CATEGORY_BILLS';
export const LABEL_REWARD_CATEGORY_HEALTH_BEAUTY =
  'LABEL_REWARD_CATEGORY_HEALTH_BEAUTY';
export const LABEL_REWARD_DESCRIPTION = 'LABEL_REWARD_DESCRIPTION';
export const LABEL_REWARD_ACCEPT_REVENUES = 'LABEL_REWARD_ACCEPT_REVENUES';
export const LABEL_REWARD_REDEEM_BUTTON = 'LABEL_REWARD_REDEEM_BUTTON';
export const LABEL_REWARD_EXPIRY_DATE = 'LABEL_REWARD_EXPIRY_DATE';
export const LABEL_REWARD_REDEEM_FOR = 'LABEL_REWARD_REDEEM_FOR';
export const LABEL_REWARD_REDEEM_WITH = 'LABEL_REWARD_REDEEM_WITH';
export const LABEL_REWARD_REDEEM_WITH_DESCRIPTION =
  'LABEL_REWARD_REDEEM_WITH_DESCRIPTION';
export const LABEL_REWARD_IN_PROGRESS = 'LABEL_REWARD_IN_PROGRESS';
export const LABEL_REWARD_FAILED = 'LABEL_REWARD_FAILED';
export const LABEL_REWARD_REDEEM_WITH_EXPIRED_AT_DESCRIPTION =
  'LABEL_REWARD_REDEEM_WITH_EXPIRED_AT_DESCRIPTION';
export const LABEL_REWARD_CLAIM_REWARD = 'LABEL_REWARD_CLAIM_REWARD';
export const LABEL_REWARD_CLAIM_REWARD_DESCRIPTION =
  'LABEL_REWARD_CLAIM_REWARD_DESCRIPTION';
export const LABEL_REWARD_REDEEM_AGAIN_BUTTON =
  'LABEL_REWARD_REDEEM_AGAIN_BUTTON';
export const LABEL_REWARD_STORES_ADDRESS = 'LABEL_REWARD_STORES_ADDRESS';
export const LABEL_REWARD_STORES = 'LABEL_REWARD_STORES';
export const LABEL_REWARD_STORE = 'LABEL_REWARD_STORE';
export const LABEL_REWARD = 'LABEL_REWARD';
export const LABEL_REWARD_USE_NOW = 'LABEL_REWARD_USE_NOW';
export const LABEL_REWARD_REDEEM_ERROR = 'LABEL_REWARD_REDEEM_ERROR';
export const LABEL_REWARD_INSTOCK = 'LABEL_REWARD_INSTOCK';
export const TITLE_REWARD_REDEEM_ERROR = 'TITLE_REWARD_REDEEM_ERROR';
export const TITLE_REWARD_REDEEM_FAILED = 'TITLE_REWARD_REDEEM_FAILED';
//WALLET
export const TITLE_WALLET = 'TITLE_WALLET';
export const LABEL_WALLET_ACTIVE = 'LABEL_WALLET_ACTIVE';
export const LABEL_WALLET_USED = 'LABEL_WALLET_USED';
export const LABEL_WALLET_ACTIVE_THIS_VOUCHER =
  'LABEL_WALLET_ACTIVE_THIS_VOUCHER';
export const LABEL_WALLET_USED_IN_DATE = 'LABEL_WALLET_USED_IN_DATE';

export const LABEL_WALLET_EXPIRED = 'LABEL_WALLET_EXPIRED';
export const BUTTON_WALLET_SHOW_CODE = 'BUTTON_WALLET_SHOW_CODE';
export const BUTTON_WALLET_HIDE_CODE = 'BUTTON_WALLET_HIDE_CODE';
export const LABEL_WALLET_ENDS_IN = 'LABEL_WALLET_ENDS_IN';
export const LABEL_WALLET_EXPIRES_BY = 'LABEL_WALLET_EXPIRES_BY';
export const LABEL_WALLET_ENDS_IN_NON_VOUCHER =
  'LABEL_WALLET_ENDS_IN_NON_VOUCHER';
export const LABEL_WALLET_EXPIRES_BY_NON_VOUCHER =
  'LABEL_WALLET_EXPIRES_BY_NON_VOUCHER';
export const LABEL_WALLET_HOW_TO_USE = 'LABEL_WALLET_HOW_TO_USE';
export const LABEL_WALLET_HOW_TO_USE_GRAB = 'LABEL_WALLET_HOW_TO_USE_GRAB';

export const LABEL_WALLET_USING_CODE = 'LABEL_WALLET_USING_CODE';
export const LABEL_WALLET_USING_CODE_TIP = 'LABEL_WALLET_USING_CODE_TIP';
export const LABEL_WALLET_SHOW_STAFF = 'LABEL_WALLET_SHOW_STAFF';
export const LABEL_WALLET_SHOW_STAFF_TIP = 'LABEL_WALLET_SHOW_STAFF_TIP';
export const LABEL_WALLET_USED_IN = 'LABEL_WALLET_USED_IN';
export const BUTTON_WALLET_RESTORE = 'BUTTON_WALLET_RESTORE';
export const BUTTON_WALLET_USED = 'BUTTON_WALLET_USED';
export const LABEL_WALLET_DAY = 'LABEL_WALLET_DAY';
export const LABEL_WALLET_DAYS = 'LABEL_WALLET_DAYS';
export const LABEL_WALLET_HOURS = 'LABEL_WALLET_HOURS';
export const LABEL_WALLET_HOUR = 'LABEL_WALLET_HOUR';
export const LABEL_WALLET_MINUTES = 'LABEL_WALLET_MINUTES';
export const LABEL_WALLET_MINUTE = 'LABEL_WALLET_MINUTE';
export const LABEL_WALLET_SUPPLIED_BY = 'LABEL_WALLET_SUPPLIED_BY';
//HOME
export const LABEL_RECOGNITION_TITLE = 'LABEL_RECOGNITION_TITLE';
export const NESTLE_LABEL_RECOGNITION_TITLE = 'NESTLE_LABEL_RECOGNITION_TITLE';
export const LABEL_LATEST_NEWS = 'LABEL_LATEST_NEWS';
export const LABEL_FEATURED_DOCUMENTS = 'LABEL_FEATURED_DOCUMENTS';
export const LABEL_GREETING_TITLE = 'LABEL_GREETING_TITLE';
export const LABEL_FAQ = 'LABEL_FAQ';
export const LABEL_FLEXIBLE_BENEFITS = 'LABEL_FLEXIBLE_BENEFITS';
export const LABEL_FLEXIBLE_BENEFITS_BUDGET = 'LABEL_FLEXIBLE_BENEFITS_BUDGET';
export const LABEL_TOTAL_BUDGET = 'LABEL_TOTAL_BUDGET';
export const LABEL_REMAINING_BALANCE = 'LABEL_REMAINING_BALANCE';
export const LABEL_TOTAL_SPENDING = 'LABEL_TOTAL_SPENDING';
export const LABEL_DUE_DATE = 'LABEL_DUE_DATE';
export const LABEL_EFFECTIVE_DATE = 'LABEL_EFFECTIVE_DATE';
export const LABEL_VALID_UNTIL = 'LABEL_VALID_UNTIL';
export const LABEL_REGISTERED = 'LABEL_REGISTERED';
export const LABEL_INACTIVE = 'LABEL_INACTIVE';
export const LABEL_OPTIONAL = 'LABEL_OPTIONAL';
export const LABEL_COMMING_SOON = 'LABEL_COMMING_SOON';
export const LABEL_OPEN_FOR_REGISTRATION = 'LABEL_OPEN_FOR_REGISTRATION';
export const LABEL_FINISHED = 'LABEL_FINISHED';
export const LABEL_IN_PROGRESS = 'LABEL_IN_PROGRESS';
export const LABEL_TRADE_NOW = 'LABEL_TRADE_NOW';
export const LABEL_CELEBRATED_MILESTONES = 'LABEL_CELEBRATED_MILESTONES';
export const LABEL_CORE_BENEFITS = 'LABEL_CORE_BENEFITS';
export const LABEL_TOTAL_BENEFITS_COST = 'LABEL_TOTAL_BENEFITS_COST';
export const BUTTON_VIEW_ALL = 'BUTTON_VIEW_ALL';
//FLEXIBLE-BENEFITS
export const LABEL_CURRENT_BALANCE = 'LABEL_CURRENT_BALANCE';
export const LABEL_TOP_BENEFITS = 'LABEL_TOP_BENEFITS';
export const LABEL_FLEXIBLE_BENEFITS_CATEGORY =
  'LABEL_FLEXIBLE_BENEFITS_CATEGORY';
export const LABEL_FLEXIBLE_BENEFITS_CLAIM_FOR =
  'LABEL_FLEXIBLE_BENEFITS_CLAIM_FOR';
export const LABEL_FLEXIBLE_BENEFITS_CLAIM = 'LABEL_FLEXIBLE_BENEFITS_CLAIM';
export const LABEL_FLEXIBLE_BENEFITS_NONE_VOUCHER =
  'LABEL_FLEXIBLE_BENEFITS_NONE_VOUCHER';
export const LABEL_FLEXIBLE_BENEFITS_NONE_VOUCHER_BOTTOM_SHEET =
  'LABEL_FLEXIBLE_BENEFITS_NONE_VOUCHER_BOTTOM_SHEET';
export const LABEL_FLEXIBLE_BENEFITS_CLAIM_CONFIRM_TITLE =
  'LABEL_FLEXIBLE_BENEFITS_CLAIM_CONFIRM_TITLE';
export const BUTTON_FLEXIBLE_BENEFITS_CLAIM = 'BUTTON_FLEXIBLE_BENEFITS_CLAIM';
export const LABEL_FLEXIBLE_BENEFITS_CLAIM_CONFIRM_DESCRIPTION =
  'LABEL_FLEXIBLE_BENEFITS_CLAIM_CONFIRM_DESCRIPTION';
export const LABEL_FLEXIBLE_BENEFITS_CLAIM_SUCCESS =
  'LABEL_FLEXIBLE_BENEFITS_CLAIM_SUCCESS';
export const LABEL_FLEXIBLE_BENEFITS_REMAINING_BALANCE =
  'LABEL_FLEXIBLE_BENEFITS_REMAINING_BALANCE';
export const LABEL_FLEXIBLE_BENEFITS_BIRTHDAY =
  'LABEL_FLEXIBLE_BENEFITS_BIRTHDAY';
export const LABEL_FLEXIBLE_BENEFITS_WEDDING =
  'LABEL_FLEXIBLE_BENEFITS_WEDDING';
export const LABEL_FLEXIBLE_BENEFITS_PARENTAL =
  'LABEL_FLEXIBLE_BENEFITS_PARENTAL';
export const LABEL_FLEXIBLE_BENEFITS_HEALTHCARE_PLAN =
  'LABEL_FLEXIBLE_BENEFITS_HEALTHCARE_PLAN';
export const LABEL_FLEXIBLE_BENEFITS_MEDICAL_CHECK_UP =
  'LABEL_FLEXIBLE_BENEFITS_MEDICAL_CHECK_UP';
export const BUTTON_FLEXIBLE_BENEFITS_PLACE_ORDER =
  'BUTTON_FLEXIBLE_BENEFITS_PLACE_ORDER';
export const TITLE_REWARD_CLAIM_ERROR = 'TITLE_REWARD_CLAIM_ERROR';
export const LABEL_FLEXIBLE_BENEFITS_CLAIM_CONFIRM_NON_VOUCHER =
  'LABEL_FLEXIBLE_BENEFITS_CLAIM_CONFIRM_NON_VOUCHER';
export const TITLE_TRADE_MODAL = 'TITLE_TRADE_MODAL';
export const DESCRIPTION_TRADE_MODAL = 'DESCRIPTION_TRADE_MODAL';
export const LABEL_ANNUAL_DATE_SLIDER = 'LABEL_ANNUAL_DATE_SLIDER';
export const TITLE_TRADE_SUCCESS_MODAL = 'TITLE_TRADE_SUCCESS_MODAL';
export const DESCRIPTION_TRADE_SUCCESS_MODAL =
  'DESCRIPTION_TRADE_SUCCESS_MODAL';
export const BUTTON_UNDERSTAND = 'BUTTON_UNDERSTAND';
//ACCOUNT
export const LABEL_PROFILE_TITLE = 'LABEL_PROFILE_TITLE';
export const TITLE_REMAINING_BENEFITS_VALUE = 'TITLE_REMAINING_BENEFITS_VALUE';
export const LABEL_ACCOUNT_INFORMATION = 'LABEL_ACCOUNT_INFORMATION';
export const LABEL_NOTIFICATION_CENTER = 'LABEL_NOTIFICATION_CENTER';
export const LABEL_WISHLIST = 'LABEL_WISHLIST';
export const LABEL_CUSTOMER_SUPPORT = 'LABEL_CUSTOMER_SUPPORT';
export const LABEL_FEEDBACK = 'LABEL_FEEDBACK';
export const LABEL_ACTIVITY_LOG = 'LABEL_ACTIVITY_LOG';
export const BUTTON_SAVE = 'BUTTON_SAVE';
export const FIELD_FULLNAME_LABEL = 'FIELD_FULLNAME_LABEL';
export const FIELD_NAME_LABEL = 'FIELD_NAME_LABEL';
export const FIELD_NAME_EMPTY_LABEL = 'FIELD_NAME_EMPTY_LABEL';
export const FIELD_FULLNAME_PLACEHOLDER = 'FIELD_FULLNAME_PLACEHOLDER';
export const FIELD_POSITION_LABEL = 'FIELD_POSITION_LABEL';
export const FIELD_POSITION_PLACEHOLDER = 'FIELD_POSITION_PLACEHOLDER';
export const FIELD_GENDER_LABEL = 'FIELD_GENDER_LABEL';
export const FIELD_GENDER_PLACEHOLDER = 'FIELD_GENDER_PLACEHOLDER';
export const FIELD_BIRTHDAY_LABEL = 'FIELD_BIRTHDAY_LABEL';
export const FIELD_BIRTHDAY_PLACEHOLDER = 'FIELD_BIRTHDAY_PLACEHOLDER';
export const FIELD_DEPARTMENT_SUB_DEPT_LABEL =
  'FIELD_DEPARTMENT_SUB_DEPT_LABEL';
export const FIELD_DEPARTMENT_LABEL = 'FIELD_DEPARTMENT_LABEL';
export const FIELD_DEPARTMENT_PLACEHOLDER = 'FIELD_DEPARTMENT_PLACEHOLDER';
export const FIELD_STARTDATE_LABEL = 'FIELD_STARTDATE_LABEL';
export const FIELD_STARTDATE_PLACEHOLDER = 'FIELD_STARTDATE_PLACEHOLDER';
export const FIELD_WORK_EMAIL_LABEL = 'FIELD_WORK_EMAIL_LABEL';
export const FIELD_WORK_EMAIL_PLACEHOLDER = 'FIELD_WORK_EMAIL_PLACEHOLDER';
export const FIELD_LOCATION_LABEL = 'FIELD_LOCATION_LABEL';
export const FIELD_LOCATION_PLACEHOLDER = 'FIELD_LOCATION_PLACEHOLDER';
export const FIELD_PHONE_NUMBER_LABEL = 'FIELD_PHONE_NUMBER_LABEL';
export const FIELD_PHONE_NUMBER = 'FIELD_PHONE_NUMBER';
export const FIELD_PHONE_NUMBER_EMPTY = 'FIELD_PHONE_NUMBER_EMPTY';
export const FIELD_PHONE_NUMBER_PLACEHOLDER = 'FIELD_PHONE_NUMBER_PLACEHOLDER';
export const FIELD_PERSONAL_EMAIL_LABEL = 'FIELD_PERSONAL_EMAIL_LABEL';
export const FIELD_PERSONAL_EMAIL_PLACEHOLDER =
  'FIELD_PERSONAL_EMAIL_PLACEHOLDER';
export const FIELD_PERSONAL_EMAIL_OPTIONAL_LABEL =
  'FIELD_PERSONAL_EMAIL_OPTIONAL_LABEL';
export const FIELD_PERSONAL_EMAIL_PLACEHOLDER_OPTIONAL_LABEL =
  'FIELD_PERSONAL_EMAIL_PLACEHOLDER_OPTIONAL_LABEL';
export const LABEL_EMAIL_SUPPORT = 'LABEL_EMAIL_SUPPORT';
export const LABEL_PHONE_SUPPORT = 'LABEL_PHONE_SUPPORT';
export const LABEL_FACEBOOK_SUPPORT = 'LABEL_FACEBOOK_SUPPORT';
export const TITLE_CHOOSE_GENDER = 'TITLE_CHOOSE_GENDER';
export const TITLE_CHOOSE_BIRTHDAY = 'TITLE_CHOOSE_BIRTHDAY';
export const LABEL_MALE = 'LABEL_MALE';
export const LABEL_FEMALE = 'LABEL_FEMALE';
export const LABEL_UNKNOWN = 'LABEL_UNKNOWN';
export const TITLE_SELECT_AVATAR = 'TITLE_SELECT_AVATAR';
export const LABEL_SECURITY = 'LABEL_SECURITY';
export const LABEL_CHANGE_PASSWORD = 'LABEL_CHANGE_PASSWORD';
export const FILED_CURRENT_PASSWORD_LABEL = 'FILED_CURRENT_PASSWORD_LABEL';
export const FILED_CURRENT_PASSWORD_PLACEHOLDER = 'FILED_CURRENT_PASSWORD_PLACEHOLDER';
export const FIELD_CONFIRM_NEW_PASSWORD_LABEL = 'FIELD_CONFIRM_NEW_PASSWORD_LABEL';
export const FIELD_CONFIRM_NEW_PASSWORD_PLACEHOLDER = 'FIELD_CONFIRM_NEW_PASSWORD_PLACEHOLDER';
export const FIELD_CONFIRM_NEW_PASSWORD_REQUIRED = 'FIELD_CONFIRM_NEW_PASSWORD_REQUIRED';
export const FIELD_CONFIRM_NEW_PASSWORD_INVALID = 'FIELD_CONFIRM_NEW_PASSWORD_INVALID';
export const LABEL_SAVE_CHANGE = 'LABEL_SAVE_CHANGE';
export const LABEL_CHANGE_SECURITY = 'LABEL_CHANGE_SECURITY';
export const LABEL_TITLE_UPDATE_SECURITY = 'LABEL_TITLE_UPDATE_SECURITY';
export const LABEL_DES_UPDATE_SECURITY = 'LABEL_DES_UPDATE_SECURITY';
export const LABEL_OK = 'LABEL_OK';
export const LABEL_NOT_MATCH_PASSWORD = 'LABEL_NOT_MATCH_PASSWORD';
export const LABEL_DUPLICATE_QUESTION = 'LABEL_DUPLICATE_QUESTION';
export const LABEL_SCAN_ME = 'LABEL_SCAN_ME';
export const LABEL_SCAN_CODE = 'LABEL_SCAN_CODE';
export const LABEL_MY_CODE = 'LABEL_MY_CODE';
export const LABEL_INPUT_EVENT_HINT = 'LABEL_INPUT_EVENT_HINT';
export const INPUT_EVENT_NAME = 'INPUT_EVENT_NAME';
export const LABEL_CHECKED_IN_SUCCESS = 'LABEL_CHECKED_IN_SUCCESS';
export const LABEL_KEEP_CODE_CENTER_THE_BOX = 'LABEL_KEEP_CODE_CENTER_THE_BOX';
export const LABEL_MY_QR_CODE = 'LABEL_MY_QR_CODE';
export const LABEL_USE_CODE_TO_CHECK_EVENT = 'LABEL_USE_CODE_TO_CHECK_EVENT';
export const LABEL_CHECKED_IN_FAILED = 'LABEL_CHECKED_IN_FAILED';
export const LABEL_CHECKED_IN_ALREADY = 'LABEL_CHECKED_IN_ALREADY';
export const DELETE_TEXT = 'DELETE_TEXT';
//PAYMENT
export const TITLE_PAYMENT = 'TITLE_PAYMENT';
export const LABEL_PAYMENT_FLEXIBLE_BENEFITS_BALANCE_METHOD =
  'LABEL_PAYMENT_FLEXIBLE_BENEFITS_BALANCE_METHOD';
export const LABEL_PAYMENT_ATM_IB_METHOD = 'LABEL_PAYMENT_ATM_IB_METHOD';
export const LABEL_PAYMENT_VISA_OTHERS_METHOD =
  'LABEL_PAYMENT_VISA_OTHERS_METHOD';
export const LABEL_PAYMENT_USE_CURRENT_BALANCE =
  'LABEL_PAYMENT_USE_CURRENT_BALANCE';
//BUTTON
export const BUTTON_NEXT = 'BUTTON_NEXT';
export const BUTTON_BACK = 'BUTTON_BACK';
export const BUTTON_SUBMIT = 'BUTTON_SUBMIT';
export const BUTTON_SUBMIT_RECOGNITION = 'BUTTON_SUBMIT_RECOGNITION';
export const BUTTON_SUBMIT_SURVEY = 'BUTTON_SUBMIT_SURVEY';
export const BUTTON_CHANGE_PASSWORD = 'BUTTON_CHANGE_PASSWORD';
export const BUTTON_LOGOUT = 'BUTTON_LOGOUT';
export const BUTTON_CONFIRM = 'BUTTON_CONFIRM';
export const BUTTON_CANCEL = 'BUTTON_CANCEL';
export const BUTTON_RESET = 'BUTTON_RESET';
export const BUTTON_APPLY = 'BUTTON_APPLY';
export const BUTTON_CONTINUE = 'BUTTON_CONTINUE';
export const BUTTON_IN_PROGRESS = 'BUTTON_IN_PROGRESS';
//COMMON
export const COMMON_LOADING = 'COMMON_LOADING';
export const COMMON_NO_INTERNET = 'COMMON_NO_INTERNET';
export const COMMON_NO_INTERNET_TITLE = 'COMMON_NO_INTERNET_TITLE';
export const COMMON_NO_INTERNET_BUTTON = 'COMMON_NO_INTERNET_BUTTON';
export const FIELD_SEARCH_PLACEHOLDER = 'FIELD_SEARCH_PLACEHOLDER';
export const MODAL_TITLE_NOTE = 'MODAL_TITLE_NOTE';
export const LABEL_RECENT_SENDER = 'LABEL_RECENT_SENDER';
export const BUTTON_VIEW_MORE = 'BUTTON_VIEW_MORE';
export const BUTTON_VIEW_LESS = 'BUTTON_VIEW_LESS';
export const LABEL_QUANTITY = 'LABEL_QUANTITY';
export const LABEL_PACKAGE = 'LABEL_PACKAGE';
export const UP_LOAD_FILE = 'UP_LOAD_FILE';
export const TEXT_ATTACH_FILE = 'TEXT_ATTACH_FILE';
export const TEXT_OPTIONAL = 'TEXT_OPTIONAL';
export const TEXT_UPLOAD_FILE_ERR = 'TEXT_UPLOAD_FILE_ERR';
//bottom-tab
export const TAB_BAR_HOME = 'TAB_BAR_HOME';
export const TAB_BAR_NEWS = 'TAB_BAR_NEWS';
export const TAB_BAR_WALLET = 'TAB_BAR_WALLET';
export const TAB_BAR_ACCOUNT = 'TAB_BAR_ACCOUNT';
export const TAB_BAR_RECOGNITION = 'TAB_BAR_RECOGNITION';
export const TAB_BAR_AIACelebration = 'TAB_BAR_AIACelebration';
export const TAB_BAR_FLEXIBLE_BENEFITS = 'TAB_BAR_FLEXIBLE_BENEFITS';
export const TAB_BAR_WELLNESS = 'TAB_BAR_WELLNESS';
export const TAB_BAR_BENEFITS = 'TAB_BAR_BENEFITS';
//error
export const TITLE_ERROR = 'TITLE_ERROR';
export const UNKNOWN_ERROR = 'UNKNOWN_ERROR';
//MONTH
export const LABEL_JAN_MONTH = 'LABEL_JAN_MONTH';
export const LABEL_FEB_MONTH = 'LABEL_FEB_MONTH';
export const LABEL_MAR_MONTH = 'LABEL_MAR_MONTH';
export const LABEL_APR_MONTH = 'LABEL_APR_MONTH';
export const LABEL_MAY_MONTH = 'LABEL_MAY_MONTH';
export const LABEL_JUN_MONTH = 'LABEL_JUN_MONTH';
export const LABEL_JUL_MONTH = 'LABEL_JUL_MONTH';
export const LABEL_AUG_MONTH = 'LABEL_AUG_MONTH';
export const LABEL_SEP_MONTH = 'LABEL_SEP_MONTH';
export const LABEL_OCT_MONTH = 'LABEL_OCT_MONTH';
export const LABEL_NOV_MONTH = 'LABEL_NOV_MONTH';
export const LABEL_DEC_MONTH = 'LABEL_DEC_MONTH';
//APP VERSION
export const CURRENT_VERSION = 'CURRENT_VERSION';
export const LATEST_VERSION = 'LATEST_VERSION';
export const MESSAGE_UPDATE = 'MESSAGE_UPDATE';
export const UPDATE_NOW = 'UPDATE_NOW';

//RATING
export const TITLE_RATING = 'TITLE_RATING';
export const DESCRIPTION_RATING = 'DESCRIPTION_RATING';
export const BUTTON_FINISH = 'BUTTON_FINISH';
export const DESCRIPTION_RATING_SUCCESS = 'DESCRIPTION_RATING_SUCCESS';
export const QUESTION_RATING = 'QUESTION_RATING';
export const SUBTITLE_RATING = 'SUBTITLE_RATING';
export const RATING_ANSWER_PLACEHOLDER = 'RATING_ANSWER_PLACEHOLDER';

//PERMISSION MODAL
export const TITLE_PERMISSION_MODAL = 'TITLE_PERMISSION_MODAL';
export const DESCRIPTION_PERMISSION_MODAL = 'DESCRIPTION_PERMISSION_MODAL';

//Note modal
export const DESCRIPTION_NOTE_MODAL = 'DESCRIPTION_NOTE_MODAL';

export const NO_RESULTS = 'NO_RESULTS';
export const PRICE = 'PRICE';
export const REPLY = 'REPLY';
export const TYPE_YOUR_MESSAGE = 'TYPE_YOUR_MESSAGE';
export const RECOGNIZED = 'RECOGNIZED';

export const YOU_HAVE_A_NEW_NOTIFICATION = 'YOU_HAVE_A_NEW_NOTIFICATION';

export const LABEL_NEW_SURVEY_NOTIFICATION = 'LABEL_NEW_SURVEY_NOTIFICATION';

export const SURVEY_PAGE_TITLE = 'SURVEY_PAGE_TITLE';

export const CODE_COPIED = 'CODE_COPIED';
export const CONVERSION = 'CONVERSION';
export const CONVERT = 'CONVERT';
export const CONVERT_COINS_BALANCE_LABEL = 'CONVERT_COINS_BALANCE_LABEL';
export const CONVERT_BUDGET_BALANCE_LABEL = 'CONVERT_BUDGET_BALANCE_LABEL';
export const CONVERT_ALL = 'CONVERT_ALL';
export const CONVERT_COINS_INPUT_LABEL = 'CONVERT_COINS_INPUT_LABEL';
export const CONVERT_BUDGET_INPUT_LABEL = 'CONVERT_BUDGET_INPUT_LABEL';
export const AVAILABLE_TO_CONVERT = 'AVAILABLE_TO_CONVERT';
export const CONVERT_COINS_TO_FLEXIBLE_BENEFIT_BUDGET_LABEL =
  'CONVERT_COINS_TO_FLEXIBLE_BENEFIT_BUDGET_LABEL';
export const LABEL_CONVERT_COINS_TO_BUDGET = 'LABEL_CONVERT_COINS_TO_BUDGET';
export const LABEL_CONVERT_COINS_TO_BUDGET_DESCRIPTION =
  'LABEL_CONVERT_COINS_TO_BUDGET_DESCRIPTION';
export const LABEL_CONVERT_SUCCESSFUL = 'LABEL_CONVERT_SUCCESSFUL';
export const LABEL_NO_ALLOWANCES_CONFIGURED_YET =
  'LABEL_NO_ALLOWANCES_CONFIGURED_YET';

export const SORT_BY_PRICE_HIGH_TO_LOW = 'SORT_BY_PRICE_HIGH_TO_LOW';
export const SORT_BY_PRICE_LOW_TO_HIGH = 'SORT_BY_PRICE_LOW_TO_HIGH';
export const SORT_BY_NAME_A_Z = 'SORT_BY_NAME_A_Z';
export const SORT_BY_NAME_Z_A = 'SORT_BY_NAME_Z_A';
export const SORT_BY = 'SORT_BY';
export const TITLE_OTHER_SCHEMES = 'TITLE_OTHER_SCHEMES';
export const STEPS = 'STEPS';
export const DONE = 'DONE';
export const TITLE_RECOGNITION_SCHEME = 'TITLE_RECOGNITION_SCHEME';
export const TITLE_SELECT_COWORKER = 'TITLE_SELECT_COWORKER';
export const TITLE_ALLOCATE_POINTS = 'TITLE_ALLOCATE_POINTS';
export const LABEL_YOUR_TEAMMATE = 'LABEL_YOUR_TEAMMATE';
export const BUTTON_ADD = 'BUTTON_ADD';
export const LABEL_RECOGNITION_SCHEME = 'LABEL_RECOGNITION_SCHEME';
export const LABEL_PARTICIPANTS = 'LABEL_PARTICIPANTS';
export const LABEL_SELECT_LEVEL_POINTS = 'LABEL_SELECT_LEVEL_POINTS';
export const LABEL_ATTACHMENT = 'LABEL_ATTACHMENT';
export const LABEL_SELECT_A_FILE = 'LABEL_SELECT_A_FILE';
export const LABEL_APPLY_THIS_MESSAGE_FOR_ALL_PARTICIPANTS =
  'LABEL_APPLY_THIS_MESSAGE_FOR_ALL_PARTICIPANTS';
export const LABEL_LEVEL_POINTS = 'LABEL_LEVEL_POINTS';
export const PLACEHOLDER_LEAVE_A_MESSAGE = 'PLACEHOLDER_LEAVE_A_MESSAGE';
export const LABEL_YOUR_SUBMISSION_HAS_BEEN_SENT =
  'LABEL_YOUR_SUBMISSION_HAS_BEEN_SENT';
export const TITLE_SUBMIT_SUCCESSFULLY = 'TITLE_SUBMIT_SUCCESSFULLY';
export const LABEL_STATUS_APPROVED = 'LABEL_STATUS_APPROVED';
export const LABEL_STATUS_PENDING = 'LABEL_STATUS_PENDING';
export const LABEL_STATUS_REJECTED = 'LABEL_STATUS_REJECTED';
export const LABEL_CHANGE_ATTACHMENT = 'LABEL_CHANGE_ATTACHMENT';
export const LABEL_COMMENTS = 'LABEL_COMMENTS';
export const BUTTON_SUBMIT_RECOGNITION_COMMENT =
  'BUTTON_SUBMIT_RECOGNITION_COMMENT';
export const LABEL_EDIT = 'LABEL_EDIT';
export const TITLE_EDIT_RECOGNITION_MESSAGE = 'TITLE_EDIT_RECOGNITION_MESSAGE';
export const LABEL_GIVE_COMMENT = 'LABEL_GIVE_COMMENT';
export const LABEL_PLEASE_SELECT_A_LEVEL_POINTS =
  'LABEL_PLEASE_SELECT_A_LEVEL_POINTS';
export const LABEL_COMMENT_MUST_HAVE_AT_LEAST_10_WORDS =
  'LABEL_COMMENT_MUST_HAVE_AT_LEAST_10_WORDS';
export const TITLE_FILTER = 'TITLE_FILTER';
export const LABEL_PROGRAM = 'LABEL_PROGRAM';
export const LABEL_STATUS = 'LABEL_STATUS';
export const LABEL_TIME = 'LABEL_TIME';
export const LABEL_RECOGNITION_TYPE = 'LABEL_RECOGNITION_TYPE';
export const LABEL_RECOGNITION_TYPE_P2P = 'LABEL_RECOGNITION_TYPE_P2P';
export const LABEL_RECOGNITION_TYPE_GROUP = 'LABEL_RECOGNITION_TYPE_GROUP';
export const LABEL_DEPARTMENT = 'LABEL_DEPARTMENT';
export const LABEL_SUB_DEPARTMENT = 'LABEL_SUB_DEPARTMENT';
export const LABEL_FUNCTION = 'LABEL_FUNCTION';
export const LABEL_LOCATION = 'LABEL_LOCATION';
export const LABEL_FINISH = 'LABEL_FINISH';
export const LABEL_ALL = 'LABEL_ALL';
export const LABEL_TOTAL_FLEXIBLE_BENEFITS_BUDGET =
  'LABEL_TOTAL_FLEXIBLE_BENEFITS_BUDGET';
export const LABEL_MY_BENEFITS = 'LABEL_MY_BENEFITS';
export const LABEL_HISTORY = 'LABEL_HISTORY';
export const LABEL_FLEXIBLE_BENEFIT_INFO_USED =
  'LABEL_FLEXIBLE_BENEFIT_INFO_USED';
export const LABEL_FLEXIBLE_BENEFIT_INFO_REMAINING =
  'LABEL_FLEXIBLE_BENEFIT_INFO_REMAINING';
export const LABEL_CURRENT_POINTS_TO_GET = 'LABEL_CURRENT_POINTS_TO_GET';

export const LABEL_TO_FLEXIBLE_BENEFITS_BUDGET =
  'LABEL_TO_FLEXIBLE_BENEFITS_BUDGET';
export const LABEL_PAYMENT_FOR_BENEFIT = 'LABEL_PAYMENT_FOR_BENEFIT';
export const LABEL_FROM_COMPANY = 'LABEL_FROM_COMPANY';
export const LABEL_REFUND_FROM_FAILED_ORDER = 'LABEL_REFUND_FROM_FAILED_ORDER';
export const LABEL_CONVERT_POINTS_TO_GET = 'LABEL_CONVERT_POINTS_TO_GET';
export const LABEL_CHANGE_EXPIRY_DATE = 'LABEL_CHANGE_EXPIRY_DATE';
export const LABEL_WALLET_EXPIRATION = 'LABEL_WALLET_EXPIRATION';
export const LABEL_TOP_UP_WALLET = 'LABEL_TOP_UP_WALLET';
export const LABEL_REGISTER_ALLOWANCE = 'LABEL_REGISTER_ALLOWANCE';
export const LABEL_FLEXIBLE_BENEFITS_INFO_BUDGET =
  'LABEL_FLEXIBLE_BENEFITS_INFO_BUDGET';
export const LABEL_POINT_TO_GIVE_BALANCE = 'LABEL_POINT_TO_GIVE_BALANCE';
export const LABEL_POINT_TO_GIVE_TOTAL = 'LABEL_POINT_TO_GIVE_TOTAL';
export const TITLE_RECOGNITION_SCHEME_ERROR = 'TITLE_RECOGNITION_SCHEME_ERROR';

export const YOU_HAVE_EXCEED_THE_LIMIT_RECOGNITION_POINT =
  'YOU_HAVE_EXCEED_THE_LIMIT_RECOGNITION_POINT';

export const TITLE_SELF_RECOGNITION_SUCCESS = 'TITLE_SELF_RECOGNITION_SUCCESS';
export const DESCRIPTION_SELF_RECOGNITION_SUCCESS =
  'DESCRIPTION_SELF_RECOGNITION_SUCCESS';
export const TITLE_PONT_KUDOS = 'TITLE_PONT_KUDOS';
export const TITLE_POINT_COINS_SPARK = 'TITLE_POINT_COINS_SPARK';
export const TITLE_PONT_SPARK = 'TITLE_PONT_SPARK';
export const TITLE_POINT_COINS_KUDOS = 'TITLE_POINT_COINS_KUDOS';
export const TOTAL_KUDOS_RECEIVED_ALL_TIME = 'TOTAL_KUDOS_RECEIVED_ALL_TIME';
export const TOTAL_KUDOS_SENT_ALL_TIME = 'TOTAL_KUDOS_SENT_ALL_TIME';

export const TOTAL_RECOGNITIONS_RECEIVED = 'TOTAL_RECOGNITIONS_RECEIVED';
export const TOTAL_RECOGNITIONS_SENT = 'TOTAL_RECOGNITIONS_SENT';
export const LABEL_ME = 'LABEL_ME';
export const LABEL_REASON = 'LABEL_REASON';
export const LABEL_SELECT_ONE_SCHEME = 'LABEL_SELECT_ONE_SCHEME';
export const LABEL_DESCRIPTION = 'LABEL_DESCRIPTION';

export const TITLE_RECOGNITION_SELF = 'TITLE_RECOGNITION_SELF';
export const TITLE_RECOGNITION_P2P = 'TITLE_RECOGNITION_P2P';
export const TAB_RECOGNITION_SELF = 'TAB_RECOGNITION_SELF';
export const TAB_RECOGNITION_P2P = 'TAB_RECOGNITION_P2P';
export const TAB_RECOGNITION_GROUP_KUDOS = 'TAB_RECOGNITION_GROUP_KUDOS';
export const FIELD_WRITE_NOTE_PLACEHOLDER_SELF =
  'FIELD_WRITE_NOTE_PLACEHOLDER_SELF';

// Social
export const REACTIONS = 'REACTIONS';

//#region Wallet history
export const LABEL_RECOGNITION_TYPE_TOP_UP_KUDOS_BUDGET =
  'LABEL_RECOGNITION_TYPE_TOP_UP_KUDOS_BUDGET';
export const LABEL_RECOGNITION_TYPE_TOP_UP_RECEIVED_KUDOS =
  'LABEL_RECOGNITION_TYPE_TOP_UP_RECEIVED_KUDOS';
export const LABEL_RECOGNITION_TYPE_RECEIVED_RECOGNITION =
  'LABEL_RECOGNITION_TYPE_RECEIVED_RECOGNITION';
export const LABEL_RECOGNITION_TYPE_SENT_RECOGNITION =
  'LABEL_RECOGNITION_TYPE_SENT_RECOGNITION';
export const LABEL_RECOGNITION_TYPE_EXPIRED_RECOGNITION =
  'LABEL_RECOGNITION_TYPE_EXPIRED_RECOGNITION';
export const LABEL_RECOGNITION_TYPE_RECALL_RECOGNITION =
  'LABEL_RECOGNITION_TYPE_RECALL_RECOGNITION';
export const LABEL_RECOGNITION_TYPE_REWARD_DES =
  'LABEL_RECOGNITION_TYPE_REWARD_DES';
export const LABEL_RECOGNITION_TYPE_TOP_UP_KUDOS_BUDGET_DES =
  'LABEL_RECOGNITION_TYPE_TOP_UP_KUDOS_BUDGET_DES';
export const LABEL_RECOGNITION_TYPE_TOP_UP_RECEIVED_KUDOS_DES =
  'LABEL_RECOGNITION_TYPE_TOP_UP_RECEIVED_KUDOS_DES';
export const LABEL_RECOGNITION_TYPE_RECEIVED_RECOGNITION_DES =
  'LABEL_RECOGNITION_TYPE_RECEIVED_RECOGNITION_DES';
export const LABEL_RECOGNITION_TYPE_SENT_RECOGNITION_DES =
  'LABEL_RECOGNITION_TYPE_SENT_RECOGNITION_DES';
export const LABEL_RECOGNITION_TYPE_EXPIRED_RECOGNITION_DES =
  'LABEL_RECOGNITION_TYPE_EXPIRED_RECOGNITION_DES';
export const LABEL_RECOGNITION_TYPE_GROUP_RECOGNITION_DES =
  'LABEL_RECOGNITION_TYPE_GROUP_RECOGNITION_DES';
export const LABEL_RECOGNITION_TYPE_RECALL_RECOGNITION_DES =
  'LABEL_RECOGNITION_TYPE_RECALL_RECOGNITION_DES';
//#endregion  Wallet history

// No internet
export const LABEL_TRY_AGAIN_BUTTON = 'LABEL_TRY_AGAIN_BUTTON';
export const LABEL_TRY_AGAIN_TITLE = 'LABEL_TRY_AGAIN_TITLE';
export const LABEL_TRY_AGAIN_DESCRIPTION = 'LABEL_TRY_AGAIN_DESCRIPTION';
