//LOGIN ==============================================
export const UPDATE_LOGIN_FORM = 'AUTH.UPDATE.LOGIN.FORM';
export const REFRESH_LOGIN_FORM = 'REFRESH.LOGIN.FORM';
export const LOGIN = 'AUTH.LOGIN';
//REGISTER ===========================================
export const UPDATE_REGISTRATION_FORM = 'AUTH.UPDATE.REGISTER.FORM';
export const REFRESH_REGISTRATION_FORM = 'REFRESH_REGISTER.FORM';
export const REGISTER = 'AUTH.REGISTER';
export const SET_SECURITY_QUESTIONS = 'AUTH.SET.SECURITY.QUESTIONS';
export const REFRESH_SECURITY_QUESTION_FORM = 'REFRESH.SECURITY.QUESTION.FORM';
export const CHANGE_VISIBLE_USERNAME_MODAL = 'CHANGE.VISIBLE.USERNAME.MODAL';
//FORGOT PASSWORD ====================================
export const UPDATE_FORGOT_PASSWORD_FORM = 'AUTH.UPDATE.FORGOT.PASSWORD.FORM';
export const REFRESH_FORGOT_PASSWORD_FORM = 'REFRESH.FORGOT.PASSWORD.FORM';
export const REFRESH_NEW_PASSWORD_FORM = 'REFRESH.NEW.PASSWORD.FORM';
//SESSION ============================================
export const SET_TOKEN_SESSION = 'SET.TOKEN.SESSION';
//USER
export const SET_USER = 'SET.USER';
export const REMOVE_USER = 'REMOVE.USER';
export const UPDATE_RE_AUTH_CONFIRM = 'UPDATE_RE_AUTH_CONFIRM';
export const TYPE_LOGIN_USER = 'TYPE.LOGIN.USER';
export const GET_FEATURES = 'GET.FEATURES';
export const SET_FEATURES = 'SET.FEATURES';
