import Empty from '@resources/build_version/Empty';
import SVG_WELCOME_LOG from '../../../assets/svg/logo-generic-intro.svg';
import AIA_BENEFITS from '../../../assets/image/EVE-Benefits.png';

export default {
  lang: {
    vi: {
      TITLE_RECOGNITION_POINTS: 'Điểm',
      TITLE_RECOGNITION_POINT: 'Điểm',
      TITLE_RECOGNITION_POINTS_FOR_NOTIFICATION: 'Điểm',
      TITLE_RECOGNITION_POINTS_NEW: 'Điểm',
      TITLE_WELCOME:
        'Chào mừng đến với\nNền tảng Phúc lợi nhân viên\nhàng đầu Việt Nam',
      TITLE_MY_REWARDS: 'Phần thưởng',
      TITLE_SENT_RECOGNITION_POINTS: 'Khen thưởng \nđã gửi',
      TITLE_REWARD_COINS: 'Xu',
      TITLE_RECEIVED_RECOGNITIONS: 'Khen thưởng \nđã nhận',
      LABEL_GIVE_POINT: 'Điểm',
      LABEL_FLEX_POINTS: 'Xu',
      LABEL_FLEX_POINT: 'Xu',
      LABEL_FLEX_POINTS_FOR_NOTIFICATION: 'Xu',
      LABEL_GIVING_RECOGNITION_POINT: 'Số điểm bạn muốn tặng',
      LABEL_RATING_VALUE_CRITERIA:
        'Đâu là giá trị thích hợp nhất với khen thưởng của bạn?',
      FIELD_NOTE_MINIMUM_WORDS_REQUIRED: 'Lời nhắn phải có ít nhất 10 từ',
      MODAL_DESCRIPTION_SEND_RECOGNITION_SMALLER:
        'Nhân viên này chỉ có thể nhận {0} trong kỳ này, bạn có muốn tiếp tục không?',
      MODAL_DESCRIPTION_SEND_RECOGNITION_ZERO:
        'Nhân viên này không thể nhận thêm xu trong giai đoạn này, bạn có chắc muốn tiếp tục?',
      TITLE_NEWS_AND_DOCUMENTS: 'Tin tức',
      LABEL_DOCUMENTS: 'Tài liệu',
      LABEL_DOCUMENTS_NOTIFICATION: 'Tài liệu mới',
      LABEL_REWARD_CATEGORY: 'Chọn phần thưởng',
      LABEL_FEATURED_DOCUMENTS: 'Tài liệu',
      LABEL_FAQ: 'Những điều cần biết',
      MODAL_DESCRIPTION_USERNAME:
        'Tên người dùng là email công ty của bạn, ngoại trừ những trường hợp khác được thông báo bởi phòng Nhân sự.',
      FIELD_DEPARTMENT_LABEL: 'Phòng',
      FIELD_DEPARTMENT_PLACEHOLDER: 'Phòng',
      FIELD_POSITION_LABEL: 'Chức vụ',
      FIELD_POSITION_PLACEHOLDER: 'Chức vụ',
      FIELD_LOCATION_LABEL: 'Đơn vị',
      FIELD_LOCATION_PLACEHOLDER: 'Đơn vị',
      FIELD_WORK_EMAIL_LABEL: 'Email công việc',
      FIELD_WORK_EMAIL_PLACEHOLDER: 'Email công việc',
      BUTTON_LEARN_MORE_RECOGNITION: 'Tìm hiểu về Cổng Khen Thưởng',
      TITLE_MAKE_A_RECOGNITION: 'Khen thưởng',
      TITLE_OTHER_SCHEMES: 'Khen thưởng khác',
      FIELD_SEARCH_NAME_PLACEHOLDER: 'Vui lòng nhập tên đồng nghiệp',
      BUTTON_SUBMIT_RECOGNITION: 'Gửi',
      BUTTON_SUBMIT_SURVEY: 'Gửi',
      DESCRIPTION_SEND_RECOGNITION_SUCCESS:
        'Số dư còn lại: {}\nHãy sử dụng số điểm này để khen thưởng các đồng nghiệp khác trước ngày **',
      LABEL_THE_LATEST: 'Mới nhất',
      LABEL_THE_OLDEST: 'Cũ nhất',
      LABEL_LISTS: 'Nhận được',
      LABEL_SEND: 'Đã gửi',
      SORT_BY_PRICE_LOW_TO_HIGH: 'Giá: Thấp đến cao',
      SORT_BY_PRICE_HIGH_TO_LOW: 'Giá: Cao đến thấp',
      FIELD_WRITE_NOTE_PLACEHOLDER: 'Bạn muốn chia sẻ với họ điều gì?',
      LABEL_LATEST_NEWS: 'Tin tức gần đây',
      LABEL_WALLET_SHOW_STAFF: 'Đưa nhân viên mã của bạn',
    },
    en: {
      TITLE_RECOGNITION_POINTS: 'Points',
      TITLE_RECOGNITION_POINT: 'Point',
      TITLE_RECOGNITION_POINTS_FOR_NOTIFICATION: 'Points',
      TITLE_RECOGNITION_POINTS_NEW: 'Points',
      TITLE_WELCOME: 'Welcome to Vietnam’s \nBenefits & Recognition Platform',
      TITLE_MY_REWARDS: 'My rewards',
      TITLE_SENT_RECOGNITION_POINTS: 'Sent \nRecognitions',
      TITLE_REWARD_COINS: 'Coins',
      TITLE_RECEIVED_RECOGNITIONS: 'Received \nRecognitions',
      LABEL_GIVE_POINT: 'Points',
      LABEL_FLEX_POINTS: 'Coins',
      LABEL_FLEX_POINT: 'Coin',
      LABEL_FLEX_POINTS_FOR_NOTIFICATION: 'Coins',
      LABEL_GIVING_RECOGNITION_POINT: 'Points you want to give',
      LABEL_RATING_VALUE_CRITERIA:
        'Which value best describes the reason for your recognition?',
      FIELD_NOTE_MINIMUM_WORDS_REQUIRED: 'Note must have at least 10 words',
      MODAL_DESCRIPTION_SEND_RECOGNITION_SMALLER:
        'This employee can only receive {0} in this period, are you sure you want to proceed?',
      MODAL_DESCRIPTION_SEND_RECOGNITION_ZERO:
        'This employee can not receive any more Coins in this period, are you sure you want to proceed?',
      TITLE_NEWS_AND_DOCUMENTS: 'News',
      LABEL_DOCUMENTS: 'Documents',
      LABEL_DOCUMENTS_NOTIFICATION: 'New Documents',
      LABEL_REWARD_CATEGORY: 'Choose your rewards',
      LABEL_FEATURED_DOCUMENTS: 'Documents',
      LABEL_FAQ: 'All the things you need to know',
      MODAL_DESCRIPTION_USERNAME:
        'Your username is your work email, unless advised otherwise by your HR.',
      FIELD_LOCATION_LABEL: 'Section',
      FIELD_LOCATION_PLACEHOLDER: 'Section',
      FIELD_POSITION_LABEL: 'Function',
      FIELD_POSITION_PLACEHOLDER: 'Function',
      FIELD_DEPARTMENT_LABEL: 'Department',
      FIELD_DEPARTMENT_PLACEHOLDER: 'Department',
      FIELD_WORK_EMAIL_LABEL: 'Work Email',
      FIELD_WORK_EMAIL_PLACEHOLDER: 'Work Email',
      BUTTON_LEARN_MORE_RECOGNITION: 'Learn more about Recognition Portal',
      TITLE_MAKE_A_RECOGNITION: 'Make a recognition',
      TITLE_OTHER_SCHEMES: 'Other recognitions',
      FIELD_SEARCH_NAME_PLACEHOLDER: 'Search first name',
      BUTTON_SUBMIT_RECOGNITION: 'Submit',
      BUTTON_SUBMIT_SURVEY: 'Submit',
      DESCRIPTION_SEND_RECOGNITION_SUCCESS:
        'Remaining balance: {}\nRemember to recognise other colleagues with these recognition points by **',
      LABEL_THE_LATEST: 'Latest',
      LABEL_THE_OLDEST: 'Earliest',
      LABEL_LISTS: 'Received',
      LABEL_SEND: 'Sent',
      SORT_BY_PRICE_LOW_TO_HIGH: 'Price: Low to high',
      SORT_BY_PRICE_HIGH_TO_LOW: 'Price: High to low',
      FIELD_WRITE_NOTE_PLACEHOLDER: 'Anything to share with them?',
      LABEL_LATEST_NEWS: 'Last News',
      LABEL_WALLET_SHOW_STAFF: 'Show Staff your code',
    },
  },
  setting: {
    isProfileEditable: true,
    minimumWords: 10,
    currencyUnit: 'đ',
    renderHomeCover: false,
    coinTextUnit: 'LABEL_FLEX_POINTS', //coins
    pointTextUnit: 'LABEL_FLEX_POINT', //coin
    currencyTitleSize: 'large-title',
    version: 'generic',
    recognitionTextUnit: 'TITLE_RECOGNITION_POINTS',
    isProgramRecognition: false,
    login: 'LoginNavigator',
    rewardSortBy: 'Name',
    isRegistrationEnabled: true,
  },
  palette: {
    ACCENT_COLOR: '#F86D09',
    SECONDARY_COLOR: '#02A54C',
    LIGHT_SECONDARY_COLOR: '#99ECC0',
    PINK_COLOR: '#00AEA0',
    RED_COLOR: '#00AEA0',
    STATUS_BAR_COLOR: '#68BD5E',
    VERTICAL_LINEAR_GRADIENT_BACKGROUND_COLORS: ['#68BD5E', '#00AEA4'],
    SENDER_CHAT_BACKGROUND_COLOR: '#E3F9F7',
    MESSAGE_TEMPLATE_BACKGROUND_COLOR: 'rgba(248, 109, 9, 0.15)',
  },
  styles: {
    buttonBackground: {
      backgroundColor: '#00AEA0',
    },
    noBorder: {
      borderWidth: 0,
    },
    button: {
      color: '#fff',
    },
    budget: {
      color: '#fff',
    },
    buttonBackgroundDisabled: {
      backgroundColor: '#CCCCCC',
    },
    buttonDisabled: {
      color: '#fff',
    },
  },
  image: {
    SVG_WELCOME_LOG: SVG_WELCOME_LOG,
    AIA_BENEFITS: AIA_BENEFITS,
    PLACEHOLDER_DOCUMENTS_SQUARE: require('../../../assets/image/generic-documents-square.png'),
    PLACEHOLDER_DOCUMENTS_COVER: require('../../../assets/image/generic-documents-cover.png'),
    PLACEHOLDER_NEWS_SQUARE: require('../../../assets/image/generic-news-square.png'),
    PLACEHOLDER_NEWS_COVER: require('../../../assets/image/generic-news-cover.png'),
    AIA_STOCK_1_IMAGE: require('../../../assets/image/generic-stock-documents.png'),
    SWIPER_1_BANNER_IMAGE: require('../../../assets/image/swiper-generic-1.png'),
    SWIPER_2_BANNER_IMAGE: require('../../../assets/image/swiper-generic-2.png'),
  },
  component: {
    FlexAUnit: Empty,
  },
};
