export const SET_FLEXIBLE_BENEFITS = 'SET_FLEXIBLE_BENEFITS';
export const CLEAR_FLEXIBLE_BENEFITS = 'CLEAR_FLEXIBLE_BENEFITS';
export const CLEAR_SINGLE_FLEXIBLE_BENEFIT = 'CLEAR_SINGLE_FLEXIBLE_BENEFIT';
export const SET_SINGLE_FLEXIBLE_BENEFIT = 'SET_SINGLE_FLEXIBLE_BENEFIT';
export const SET_FLEXIBLE_BENEFITS_CATEGORIES =
  'SET_FLEXIBLE_BENEFITS_CATEGORIES';
export const SET_CLAIM_FLEXIBLE_BENEFITS_EXPIRED_AT =
  'SET_CLAIM_REWARD_EXPIRED_AT';
export const SET_FLEXIBLE_BENEFITS_INFO = 'SET_FLEXIBLE_BENEFITS_INFO';
export const SET_FLEXIBLE_BENEFITS_BUDGET = 'SET_FLEXIBLE_BENEFITS_BUDGET';
export const SET_TOP_FLEXIBLE_BENEFITS = 'SET_TOP_FLEXIBLE_BENEFITS';
export const CLEAR_TOP_FLEXIBLE_BENEFITS = 'CLEAR_TOP_FLEXIBLE_BENEFITS';
export const CHANGE_STATE_WISHLIST_SINGLE_FLEXIBLE_BENEFIT =
  'CHANGE_STATE_WISHLIST_SINGLE_FLEXIBLE_BENEFIT';
export const SET_WISHLIST = 'SET_WISHLIST';
export const CLEAR_WISHLIST = 'CLEAR_WISHLIST';
export const UPDATE_QUANTITY_SINGLE_FLEXIBLE_BENEFIT =
  'UPDATE_QUANTITY_SINGLE_FLEXIBLE_BENEFIT';
export const UPDATE_OPTIONS_SINGLE_FLEXIBLE_BENEFIT =
  'UPDATE_OPTIONS_SINGLE_FLEXIBLE_BENEFIT';
export const SHOW_HIDE_CONFIRM_CLAIM_FLEXIBLE_BENEFIT =
  'SHOW_CONFIRM_CLAIM_FLEXIBLE_BENEFIT';
export const SHOW_HIDE_SUCCESS_CLAIM_FLEXIBLE_BENEFIT =
  'SHOW_HIDE_SUCCESS_CLAIM_FLEXIBLE_BENEFIT';
export const SHOW_HIDE_ERROR_CLAIM_FLEXIBLE_BENEFIT =
  'SHOW_HIDE_ERROR_CLAIM_FLEXIBLE_BENEFIT';
export const UPDATE_TOTAL_WISH_LIST = 'UPDATE_TOTAL_WISH_LIST';
export const SET_REFRESHING = 'SET_REFRESHING';
export const SET_FLEXIBLE_CATEGORIES = 'SET_FLEXIBLE_CATEGORIES';
export const CLEAR_FLEXIBLE_CATEGORIES = 'CLEAR_FLEXIBLE_CATEGORIES';
export const UPDATE_PERSONAL_EMAIL_SINGLE_FLEXIBLE_BENEFIT =
  'UPDATE_PERSONAL_EMAIL_SINGLE_FLEXIBLE_BENEFIT';
export const UPDATE_PHONE_NUMBER_SINGLE_FLEXIBLE_BENEFIT =
  'UPDATE_PHONE_NUMBER_SINGLE_FLEXIBLE_BENEFIT';
export const UPDATE_FULL_NAME_SINGLE_FLEXIBLE_BENEFIT =
  'UPDATE_FULL_NAME_SINGLE_FLEXIBLE_BENEFIT;';
export const UPDATE_ERROR_MESSAGES_NON_VOUCHER =
  'UPDATE_ERROR_MESSAGES_NON_VOUCHER';
export const SET_FLEXIBLE_CATEGORY = 'SET_FLEXIBLE_CATEGORY';
export const SET_TRADE_MODAL_VISIBLE = 'SET_TRADE_MODAL_VISIBLE';
export const SET_TRADE_SUCCESS_MODAL_VISIBLE =
  'SET_TRADE_SUCCESS_MODAL_VISIBLE';
export const SET_TRADE_OFF_SETTING = 'SET_TRADE_OFF_SETTING';
export const UPDATE_CELEBRATE_MILESTONES_STUTUS =
  'UPDATE_CELEBRATE_MILESTONES_STUTUS';
export const SET_SEARCH_REWARDS_QUERY = 'flex/SET_SEARCH_REWARDS_QUERY';
export const CLEAR_SEARCH_REWARDS_QUERY = 'CLEAR_SEARCH_REWARDS_QUERY';
export const CHANGE_SORT_REWARDS = 'CHANGE_SORT_REWARDS';
export const UPDATE_BUDGET_AFTER_CONVERT = 'UPDATE_BUDGET_AFTER_CONVERT';
export const SET_FLEXIBLE_BENEFITS_INFO_BY_CATEGORY =
  'SET_FLEXIBLE_BENEFITS_INFO_BY_CATEGORY';
export const CHANGE_BENEFIT_INFO_TAB = 'CHANGE_BENEFIT_INFO_TAB';
export const SET_FLEXIBLE_BENEFIT_WALLET_HISTORIES = 'SET_FLEXIBLE_BENEFIT_WALLET_HISTORIES';
export const CLEAR_FLEXIBLE_BENEFIT_WALLET_HISTORIES = 'CLEAR_FLEXIBLE_BENEFIT_WALLET_HISTORIES';
export const SET_FLEXIBLE_BENEFIT_LOADING = 'SET_FLEXIBLE_BENEFIT_LOADING';

// wellness
export const GENERATE_WELLNESS_TOKEN = 'GENERATE_WELLNESS_TOKEN';
export const GENERATE_WELLNESS_TOKEN_SUCCESS = 'GENERATE_WELLNESS_TOKEN_SUCCESS';
export const GENERATE_WELLNESS_TOKEN_FAILED = 'GENERATE_WELLNESS_TOKEN_FAILED';