export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';
export const READ_NOTIFICATION = 'READ_NOTIFICATION';
export const CLEAR_NOTIFICATIONS = 'CLEAR_NOTIFICATIONS';
export const READ_ALL_NOTIFICATION = 'READ_ALL_NOTIFICATION';
export const CHANGE_NOTIFICATION_CATEGORY = 'CHANGE_NOTIFICATION_CATEGORY';
export const GET_TOP_NOTIFICATION = 'GET_TOP_NOTIFICATION';
export const GET_TOP_NOTIFICATION_SUCCESS = 'GET_TOP_NOTIFICATION_SUCCESS';
export const GET_TOP_NOTIFICATION_FAILED = 'GET_TOP_NOTIFICATION_FAILED';

export const SHOW_LOADING_NOTIFICATION = 'SHOW_LOADING_NOTIFICATION';
export const HIDE_LOADING_NOTIFICATION = 'HIDE_LOADING_NOTIFICATION';
