export const SET_USER_PROFILE = 'SET_USER_PROFILE';
export const SET_UPDATE_USER_PROFILE_FORM = 'SET_UPDATE_USER_PROFILE_FORM';
export const INIT_UPDATE_USER_PROFILE_FORM = 'INIT_UPDATE_USER_PROFILE_FORM';
export const UPDATE_PASSWORD_FORM = 'UPDATE_PASSWORD_FORM';
export const SET_ANSWER_SECURITY_QUESTIONS = 'SET_ANSWER_SECURITY_QUESTIONS';
export const UPDATE_SECURITY_FORM = 'UPDATE_SECURITY_FORM';
export const TOGGLE_MODAL_SUCCESS = 'TOGGLE_MODAL_SUCCESS';
export const RESET_FORM_SECURITY = 'RESET_FORM_SECURITY';

